; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\diskio.o --depend=cnn_1\diskio.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O3 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\diskio.crf ../Middlewares/Third_Party/FatFs/src/diskio.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.disk_initialize||, CODE, READONLY, ALIGN=2

disk_initialize PROC
        LDR      r1,|L1.36|
        MOVS     r2,#0
        PUSH     {r4,lr}
        LDRB     r3,[r1,r0]
        CBNZ     r3,|L1.30|
        MOVS     r2,#1
        STRB     r2,[r1,r0]
        ADD      r2,r1,r0,LSL #2
        ADD      r0,r0,r1
        LDR      r1,[r2,#4]
        LDRB     r0,[r0,#8]
        LDR      r1,[r1,#0]
        BLX      r1
        MOV      r2,r0
|L1.30|
        MOV      r0,r2
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.36|
        DCD      disk

        AREA ||i.disk_ioctl||, CODE, READONLY, ALIGN=2

disk_ioctl PROC
        LDR      r3,|L2.20|
        PUSH     {r4,r5}
        ADD      r4,r3,r0,LSL #2
        ADD      r0,r0,r3
        LDR      r3,[r4,#4]
        LDRB     r0,[r0,#8]
        LDR      r3,[r3,#0x10]
        POP      {r4,r5}
        BX       r3
        ENDP

|L2.20|
        DCD      disk

        AREA ||i.disk_read||, CODE, READONLY, ALIGN=2

disk_read PROC
        PUSH     {r4,r5}
        LDR      r4,|L3.24|
        ADD      r5,r4,r0,LSL #2
        ADD      r0,r0,r4
        LDR      r4,[r5,#4]
        LDRB     r0,[r0,#8]
        LDR      r4,[r4,#8]
        MOV      r12,r4
        POP      {r4,r5}
        BX       r12
        ENDP

        DCW      0x0000
|L3.24|
        DCD      disk

        AREA ||i.disk_status||, CODE, READONLY, ALIGN=2

disk_status PROC
        LDR      r1,|L4.16|
        ADD      r2,r1,r0,LSL #2
        ADD      r0,r0,r1
        LDR      r1,[r2,#4]
        LDRB     r0,[r0,#8]
        LDR      r1,[r1,#4]
        BX       r1
        ENDP

|L4.16|
        DCD      disk

        AREA ||i.disk_write||, CODE, READONLY, ALIGN=2

disk_write PROC
        PUSH     {r4,r5}
        LDR      r4,|L5.24|
        ADD      r5,r4,r0,LSL #2
        ADD      r0,r0,r4
        LDR      r4,[r5,#4]
        LDRB     r0,[r0,#8]
        LDR      r4,[r4,#0xc]
        MOV      r12,r4
        POP      {r4,r5}
        BX       r12
        ENDP

        DCW      0x0000
|L5.24|
        DCD      disk

        AREA ||i.get_fattime||, CODE, READONLY, ALIGN=1

get_fattime PROC
        MOVS     r0,#0
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Middlewares/Third_Party/FatFs/src/diskio.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___8_diskio_c_fd8865f0____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___8_diskio_c_fd8865f0____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___8_diskio_c_fd8865f0____REVSH|
#line 402
|__asm___8_diskio_c_fd8865f0____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___8_diskio_c_fd8865f0____RRX|
#line 587
|__asm___8_diskio_c_fd8865f0____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT disk_initialize [CODE]
        EXPORT disk_ioctl [CODE]
        EXPORT disk_read [CODE]
        EXPORT disk_status [CODE]
        EXPORT disk_write [CODE]
        EXPORT get_fattime [CODE,WEAK]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT disk [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
