; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\stm32f7xx_hal_dma_ex.o --depend=cnn_1\stm32f7xx_hal_dma_ex.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O0 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\stm32f7xx_hal_dma_ex.crf ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.DMA_MultiBufferSetConfig||, CODE, READONLY, ALIGN=1

DMA_MultiBufferSetConfig PROC
        PUSH     {r4,lr}
        LDR      r4,[r0,#0]
        STR      r3,[r4,#4]
        LDR      r4,[r0,#8]
        CMP      r4,#0x40
        BNE      |L1.22|
        LDR      r4,[r0,#0]
        STR      r2,[r4,#8]
        LDR      r4,[r0,#0]
        STR      r1,[r4,#0xc]
        B        |L1.30|
|L1.22|
        LDR      r4,[r0,#0]
        STR      r1,[r4,#8]
        LDR      r4,[r0,#0]
        STR      r2,[r4,#0xc]
|L1.30|
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_DMAEx_ChangeMemory||, CODE, READONLY, ALIGN=1

HAL_DMAEx_ChangeMemory PROC
        MOV      r3,r0
        CBNZ     r2,|L2.10|
        LDR      r0,[r3,#0]
        STR      r1,[r0,#0xc]
        B        |L2.14|
|L2.10|
        LDR      r0,[r3,#0]
        STR      r1,[r0,#0x10]
|L2.14|
        MOVS     r0,#0
        BX       lr
        ENDP


        AREA ||i.HAL_DMAEx_MultiBufferStart||, CODE, READONLY, ALIGN=1

HAL_DMAEx_MultiBufferStart PROC
        PUSH     {r4-r10,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r5,r3
        LDR      r8,[sp,#0x20]
        MOV      r9,#0
        LDR      r0,[r4,#8]
        CMP      r0,#0x80
        BNE      |L3.36|
        LSLS     r0,r0,#1
        STR      r0,[r4,#0x54]
        MOV      r9,#1
        B        |L3.120|
|L3.36|
        NOP      
        LDRB     r0,[r4,#0x34]
        CMP      r0,#1
        BNE      |L3.52|
        MOVS     r0,#2
|L3.48|
        POP      {r4-r10,pc}
|L3.52|
        MOVS     r0,#1
        STRB     r0,[r4,#0x34]
        NOP      
        LDRB     r0,[r4,#0x35]
        CMP      r0,#1
        BNE      |L3.116|
        MOVS     r0,#2
        STRB     r0,[r4,#0x35]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x40000
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        STR      r5,[r0,#0x10]
        MOV      r3,r8
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r4
        BL       DMA_MultiBufferSetConfig
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        B        |L3.120|
|L3.116|
        MOV      r9,#2
|L3.120|
        MOV      r0,r9
        B        |L3.48|
        ENDP


        AREA ||i.HAL_DMAEx_MultiBufferStart_IT||, CODE, READONLY, ALIGN=2

HAL_DMAEx_MultiBufferStart_IT PROC
        PUSH     {r4-r10,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r5,r3
        LDR      r8,[sp,#0x20]
        MOV      r9,#0
        LDR      r0,[r4,#8]
        CMP      r0,#0x80
        BNE      |L4.36|
        LSLS     r0,r0,#1
        STR      r0,[r4,#0x54]
        MOVS     r0,#1
|L4.32|
        POP      {r4-r10,pc}
|L4.36|
        NOP      
        LDRB     r0,[r4,#0x34]
        CMP      r0,#1
        BNE      |L4.50|
        MOVS     r0,#2
        B        |L4.32|
|L4.50|
        MOVS     r0,#1
        STRB     r0,[r4,#0x34]
        NOP      
        LDRB     r0,[r4,#0x35]
        CMP      r0,#1
        BNE      |L4.298|
        MOVS     r0,#2
        STRB     r0,[r4,#0x35]
        MOVS     r0,#0
        STR      r0,[r4,#0x54]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x40000
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        STR      r5,[r0,#0x10]
        MOV      r3,r8
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r4
        BL       DMA_MultiBufferSetConfig
        LDR      r1,|L4.1108|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.300|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.124|
        MOVS     r0,#0x20
        B        |L4.290|
|L4.124|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.138|
        MOVS     r0,#0x20
        B        |L4.290|
|L4.138|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.152|
        MOVS     r0,#0x20
        B        |L4.290|
|L4.152|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.166|
        MOVS     r0,#0x20
        B        |L4.290|
|L4.166|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.180|
        ASRS     r0,r0,#19
        B        |L4.290|
|L4.180|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.194|
        ASRS     r0,r0,#19
        B        |L4.290|
|L4.194|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.208|
        ASRS     r0,r0,#19
        B        |L4.290|
|L4.208|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.222|
        ASRS     r0,r0,#19
        B        |L4.290|
|L4.222|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.238|
        MOV      r0,#0x200000
        B        |L4.290|
|L4.238|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.254|
        MOV      r0,#0x200000
        B        |L4.290|
|L4.254|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.270|
        MOV      r0,#0x200000
        B        |L4.290|
|L4.270|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.286|
        MOV      r0,#0x200000
        B        |L4.290|
|L4.286|
        MOV      r0,#0x8000000
|L4.290|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x4c
        STR      r0,[r1,#0]
        B        |L4.876|
|L4.298|
        B        |L4.2316|
|L4.300|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0xa8
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.496|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.322|
        MOVS     r0,#0x20
        B        |L4.488|
|L4.322|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.336|
        MOVS     r0,#0x20
        B        |L4.488|
|L4.336|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.350|
        MOVS     r0,#0x20
        B        |L4.488|
|L4.350|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.364|
        MOVS     r0,#0x20
        B        |L4.488|
|L4.364|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.378|
        ASRS     r0,r0,#19
        B        |L4.488|
|L4.378|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.392|
        ASRS     r0,r0,#19
        B        |L4.488|
|L4.392|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.406|
        ASRS     r0,r0,#19
        B        |L4.488|
|L4.406|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.420|
        ASRS     r0,r0,#19
        B        |L4.488|
|L4.420|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.436|
        MOV      r0,#0x200000
        B        |L4.488|
|L4.436|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.452|
        MOV      r0,#0x200000
        B        |L4.488|
|L4.452|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.468|
        MOV      r0,#0x200000
        B        |L4.488|
|L4.468|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.484|
        MOV      r0,#0x200000
        B        |L4.488|
|L4.484|
        MOV      r0,#0x8000000
|L4.488|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x50
        STR      r0,[r1,#0]
        B        |L4.876|
|L4.496|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.692|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.518|
        MOVS     r0,#0x20
        B        |L4.684|
|L4.518|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.532|
        MOVS     r0,#0x20
        B        |L4.684|
|L4.532|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.546|
        MOVS     r0,#0x20
        B        |L4.684|
|L4.546|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.560|
        MOVS     r0,#0x20
        B        |L4.684|
|L4.560|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.574|
        ASRS     r0,r0,#19
        B        |L4.684|
|L4.574|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.588|
        ASRS     r0,r0,#19
        B        |L4.684|
|L4.588|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.602|
        ASRS     r0,r0,#19
        B        |L4.684|
|L4.602|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.616|
        ASRS     r0,r0,#19
        B        |L4.684|
|L4.616|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.632|
        MOV      r0,#0x200000
        B        |L4.684|
|L4.632|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.648|
        MOV      r0,#0x200000
        B        |L4.684|
|L4.648|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.664|
        MOV      r0,#0x200000
        B        |L4.684|
|L4.664|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.680|
        MOV      r0,#0x200000
        B        |L4.684|
|L4.680|
        MOV      r0,#0x8000000
|L4.684|
        LDR      r1,|L4.1112|
        SUBS     r1,r1,#0x10
        STR      r0,[r1,#0xc]
        B        |L4.876|
|L4.692|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.704|
        MOVS     r0,#0x20
        B        |L4.870|
|L4.704|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.718|
        MOVS     r0,#0x20
        B        |L4.870|
|L4.718|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.732|
        MOVS     r0,#0x20
        B        |L4.870|
|L4.732|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.746|
        MOVS     r0,#0x20
        B        |L4.870|
|L4.746|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.760|
        ASRS     r0,r0,#19
        B        |L4.870|
|L4.760|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.774|
        ASRS     r0,r0,#19
        B        |L4.870|
|L4.774|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.788|
        ASRS     r0,r0,#19
        B        |L4.870|
|L4.788|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.802|
        ASRS     r0,r0,#19
        B        |L4.870|
|L4.802|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.818|
        MOV      r0,#0x200000
        B        |L4.870|
|L4.818|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.834|
        MOV      r0,#0x200000
        B        |L4.870|
|L4.834|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.850|
        MOV      r0,#0x200000
        B        |L4.870|
|L4.850|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.866|
        MOV      r0,#0x200000
        B        |L4.870|
|L4.866|
        MOV      r0,#0x8000000
|L4.870|
        LDR      r1,|L4.1112|
        SUBS     r1,r1,#0x10
        STR      r0,[r1,#8]
|L4.876|
        LDR      r1,|L4.1108|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.1070|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.896|
        MOVS     r0,#0x10
        B        |L4.1062|
|L4.896|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.910|
        MOVS     r0,#0x10
        B        |L4.1062|
|L4.910|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.924|
        MOVS     r0,#0x10
        B        |L4.1062|
|L4.924|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.938|
        MOVS     r0,#0x10
        B        |L4.1062|
|L4.938|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.952|
        ASRS     r0,r0,#20
        B        |L4.1062|
|L4.952|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.966|
        ASRS     r0,r0,#20
        B        |L4.1062|
|L4.966|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.980|
        ASRS     r0,r0,#20
        B        |L4.1062|
|L4.980|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.994|
        ASRS     r0,r0,#20
        B        |L4.1062|
|L4.994|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1010|
        MOV      r0,#0x100000
        B        |L4.1062|
|L4.1010|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1026|
        MOV      r0,#0x100000
        B        |L4.1062|
|L4.1026|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1042|
        MOV      r0,#0x100000
        B        |L4.1062|
|L4.1042|
        LDR      r1,|L4.1108|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1058|
        MOV      r0,#0x100000
        B        |L4.1062|
|L4.1058|
        MOV      r0,#0x4000000
|L4.1062|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x4c
        STR      r0,[r1,#0]
        B        |L4.1648|
|L4.1070|
        LDR      r1,|L4.1112|
        ADDS     r1,r1,#0xa8
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.1272|
        LDR      r1,|L4.1112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1092|
        MOVS     r0,#0x10
        B        |L4.1264|
|L4.1092|
        LDR      r1,|L4.1108|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1116|
        MOVS     r0,#0x10
        B        |L4.1264|
        DCW      0x0000
|L4.1108|
        DCD      0x40026458
|L4.1112|
        DCD      0x40026010
|L4.1116|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1128|
        MOVS     r0,#0x10
        B        |L4.1264|
|L4.1128|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1140|
        MOVS     r0,#0x10
        B        |L4.1264|
|L4.1140|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1154|
        ASRS     r0,r0,#20
        B        |L4.1264|
|L4.1154|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1168|
        ASRS     r0,r0,#20
        B        |L4.1264|
|L4.1168|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1182|
        ASRS     r0,r0,#20
        B        |L4.1264|
|L4.1182|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1196|
        ASRS     r0,r0,#20
        B        |L4.1264|
|L4.1196|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1212|
        MOV      r0,#0x100000
        B        |L4.1264|
|L4.1212|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1228|
        MOV      r0,#0x100000
        B        |L4.1264|
|L4.1228|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1244|
        MOV      r0,#0x100000
        B        |L4.1264|
|L4.1244|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1260|
        MOV      r0,#0x100000
        B        |L4.1264|
|L4.1260|
        MOV      r0,#0x4000000
|L4.1264|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x68
        STR      r0,[r1,#0]
        B        |L4.1648|
|L4.1272|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.1466|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1296|
        MOVS     r0,#0x10
        B        |L4.1458|
|L4.1296|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1310|
        MOVS     r0,#0x10
        B        |L4.1458|
|L4.1310|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1322|
        MOVS     r0,#0x10
        B        |L4.1458|
|L4.1322|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1334|
        MOVS     r0,#0x10
        B        |L4.1458|
|L4.1334|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1348|
        ASRS     r0,r0,#20
        B        |L4.1458|
|L4.1348|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1362|
        ASRS     r0,r0,#20
        B        |L4.1458|
|L4.1362|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1376|
        ASRS     r0,r0,#20
        B        |L4.1458|
|L4.1376|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1390|
        ASRS     r0,r0,#20
        B        |L4.1458|
|L4.1390|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1406|
        MOV      r0,#0x100000
        B        |L4.1458|
|L4.1406|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1422|
        MOV      r0,#0x100000
        B        |L4.1458|
|L4.1422|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1438|
        MOV      r0,#0x100000
        B        |L4.1458|
|L4.1438|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1454|
        MOV      r0,#0x100000
        B        |L4.1458|
|L4.1454|
        MOV      r0,#0x4000000
|L4.1458|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x70
        STR      r0,[r1,#0xc]
        B        |L4.1648|
|L4.1466|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1480|
        MOVS     r0,#0x10
        B        |L4.1642|
|L4.1480|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1494|
        MOVS     r0,#0x10
        B        |L4.1642|
|L4.1494|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1506|
        MOVS     r0,#0x10
        B        |L4.1642|
|L4.1506|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1518|
        MOVS     r0,#0x10
        B        |L4.1642|
|L4.1518|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1532|
        ASRS     r0,r0,#20
        B        |L4.1642|
|L4.1532|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1546|
        ASRS     r0,r0,#20
        B        |L4.1642|
|L4.1546|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1560|
        ASRS     r0,r0,#20
        B        |L4.1642|
|L4.1560|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1574|
        ASRS     r0,r0,#20
        B        |L4.1642|
|L4.1574|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1590|
        MOV      r0,#0x100000
        B        |L4.1642|
|L4.1590|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1606|
        MOV      r0,#0x100000
        B        |L4.1642|
|L4.1606|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1622|
        MOV      r0,#0x100000
        B        |L4.1642|
|L4.1622|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1638|
        MOV      r0,#0x100000
        B        |L4.1642|
|L4.1638|
        MOV      r0,#0x4000000
|L4.1642|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x70
        STR      r0,[r1,#8]
|L4.1648|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.1842|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1672|
        MOVS     r0,#8
        B        |L4.1834|
|L4.1672|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1686|
        MOVS     r0,#8
        B        |L4.1834|
|L4.1686|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1698|
        MOVS     r0,#8
        B        |L4.1834|
|L4.1698|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1710|
        MOVS     r0,#8
        B        |L4.1834|
|L4.1710|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1724|
        ASRS     r0,r0,#21
        B        |L4.1834|
|L4.1724|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1738|
        ASRS     r0,r0,#21
        B        |L4.1834|
|L4.1738|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1752|
        ASRS     r0,r0,#21
        B        |L4.1834|
|L4.1752|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1766|
        ASRS     r0,r0,#21
        B        |L4.1834|
|L4.1766|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1782|
        MOV      r0,#0x80000
        B        |L4.1834|
|L4.1782|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1798|
        MOV      r0,#0x80000
        B        |L4.1834|
|L4.1798|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1814|
        MOV      r0,#0x80000
        B        |L4.1834|
|L4.1814|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1830|
        MOV      r0,#0x80000
        B        |L4.1834|
|L4.1830|
        MOV      r0,#0x2000000
|L4.1834|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x64
        STR      r0,[r1,#0]
        B        |L4.2418|
|L4.1842|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.2036|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1866|
        MOVS     r0,#8
        B        |L4.2028|
|L4.1866|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1880|
        MOVS     r0,#8
        B        |L4.2028|
|L4.1880|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1892|
        MOVS     r0,#8
        B        |L4.2028|
|L4.1892|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1904|
        MOVS     r0,#8
        B        |L4.2028|
|L4.1904|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1918|
        ASRS     r0,r0,#21
        B        |L4.2028|
|L4.1918|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1932|
        ASRS     r0,r0,#21
        B        |L4.2028|
|L4.1932|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1946|
        ASRS     r0,r0,#21
        B        |L4.2028|
|L4.1946|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1960|
        ASRS     r0,r0,#21
        B        |L4.2028|
|L4.1960|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1976|
        MOV      r0,#0x80000
        B        |L4.2028|
|L4.1976|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.1992|
        MOV      r0,#0x80000
        B        |L4.2028|
|L4.1992|
        LDR      r1,|L4.2112|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2008|
        MOV      r0,#0x80000
        B        |L4.2028|
|L4.2008|
        LDR      r1,|L4.2116|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2024|
        MOV      r0,#0x80000
        B        |L4.2028|
|L4.2024|
        MOV      r0,#0x2000000
|L4.2028|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x68
        STR      r0,[r1,#0]
        B        |L4.2418|
|L4.2036|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.2234|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2060|
        MOVS     r0,#8
        B        |L4.2226|
|L4.2060|
        LDR      r1,|L4.2116|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2074|
        MOVS     r0,#8
        B        |L4.2226|
|L4.2074|
        LDR      r1,|L4.2112|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2086|
        MOVS     r0,#8
        B        |L4.2226|
|L4.2086|
        LDR      r1,|L4.2116|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2098|
        MOVS     r0,#8
        B        |L4.2226|
|L4.2098|
        LDR      r1,|L4.2112|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2120|
        ASRS     r0,r0,#21
        B        |L4.2226|
|L4.2112|
        DCD      0x40026070
|L4.2116|
        DCD      0x40026470
|L4.2120|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2132|
        ASRS     r0,r0,#21
        B        |L4.2226|
|L4.2132|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2144|
        ASRS     r0,r0,#21
        B        |L4.2226|
|L4.2144|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2158|
        ASRS     r0,r0,#21
        B        |L4.2226|
|L4.2158|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2174|
        MOV      r0,#0x80000
        B        |L4.2226|
|L4.2174|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2190|
        MOV      r0,#0x80000
        B        |L4.2226|
|L4.2190|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2206|
        MOV      r0,#0x80000
        B        |L4.2226|
|L4.2206|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2222|
        MOV      r0,#0x80000
        B        |L4.2226|
|L4.2222|
        MOV      r0,#0x2000000
|L4.2226|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x88
        STR      r0,[r1,#0xc]
        B        |L4.2418|
|L4.2234|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2248|
        MOVS     r0,#8
        B        |L4.2412|
|L4.2248|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2262|
        MOVS     r0,#8
        B        |L4.2412|
|L4.2262|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2276|
        MOVS     r0,#8
        B        |L4.2412|
|L4.2276|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2290|
        MOVS     r0,#8
        B        |L4.2412|
|L4.2290|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2304|
        ASRS     r0,r0,#21
        B        |L4.2412|
|L4.2304|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2318|
        ASRS     r0,r0,#21
        B        |L4.2412|
|L4.2316|
        B        |L4.4012|
|L4.2318|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2330|
        ASRS     r0,r0,#21
        B        |L4.2412|
|L4.2330|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2344|
        ASRS     r0,r0,#21
        B        |L4.2412|
|L4.2344|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2360|
        MOV      r0,#0x80000
        B        |L4.2412|
|L4.2360|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2376|
        MOV      r0,#0x80000
        B        |L4.2412|
|L4.2376|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2392|
        MOV      r0,#0x80000
        B        |L4.2412|
|L4.2392|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2408|
        MOV      r0,#0x80000
        B        |L4.2412|
|L4.2408|
        MOV      r0,#0x2000000
|L4.2412|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x88
        STR      r0,[r1,#8]
|L4.2418|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.2612|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2442|
        LDR      r0,|L4.3132|
        B        |L4.2604|
|L4.2442|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2456|
        LDR      r0,|L4.3132|
        B        |L4.2604|
|L4.2456|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2470|
        LDR      r0,|L4.3132|
        B        |L4.2604|
|L4.2470|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2484|
        LDR      r0,|L4.3132|
        B        |L4.2604|
|L4.2484|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2498|
        ASRS     r0,r0,#22
        B        |L4.2604|
|L4.2498|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2510|
        ASRS     r0,r0,#22
        B        |L4.2604|
|L4.2510|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2522|
        ASRS     r0,r0,#22
        B        |L4.2604|
|L4.2522|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2536|
        ASRS     r0,r0,#22
        B        |L4.2604|
|L4.2536|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2552|
        MOV      r0,#0x40000
        B        |L4.2604|
|L4.2552|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2568|
        MOV      r0,#0x40000
        B        |L4.2604|
|L4.2568|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2584|
        MOV      r0,#0x40000
        B        |L4.2604|
|L4.2584|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2600|
        MOV      r0,#0x40000
        B        |L4.2604|
|L4.2600|
        MOV      r0,#0x1000000
|L4.2604|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x1c
        STR      r0,[r1,#0]
        B        |L4.3190|
|L4.2612|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.2806|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2636|
        LDR      r0,|L4.3132|
        B        |L4.2798|
|L4.2636|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2650|
        LDR      r0,|L4.3132|
        B        |L4.2798|
|L4.2650|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2664|
        LDR      r0,|L4.3132|
        B        |L4.2798|
|L4.2664|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2678|
        LDR      r0,|L4.3132|
        B        |L4.2798|
|L4.2678|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2692|
        ASRS     r0,r0,#22
        B        |L4.2798|
|L4.2692|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2704|
        ASRS     r0,r0,#22
        B        |L4.2798|
|L4.2704|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2716|
        ASRS     r0,r0,#22
        B        |L4.2798|
|L4.2716|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2730|
        ASRS     r0,r0,#22
        B        |L4.2798|
|L4.2730|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2746|
        MOV      r0,#0x40000
        B        |L4.2798|
|L4.2746|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2762|
        MOV      r0,#0x40000
        B        |L4.2798|
|L4.2762|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2778|
        MOV      r0,#0x40000
        B        |L4.2798|
|L4.2778|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2794|
        MOV      r0,#0x40000
        B        |L4.2798|
|L4.2794|
        MOV      r0,#0x1000000
|L4.2798|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x20
        STR      r0,[r1,#0]
        B        |L4.3190|
|L4.2806|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.3000|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2830|
        LDR      r0,|L4.3132|
        B        |L4.2992|
|L4.2830|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2844|
        LDR      r0,|L4.3132|
        B        |L4.2992|
|L4.2844|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2858|
        LDR      r0,|L4.3132|
        B        |L4.2992|
|L4.2858|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2872|
        LDR      r0,|L4.3132|
        B        |L4.2992|
|L4.2872|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2886|
        ASRS     r0,r0,#22
        B        |L4.2992|
|L4.2886|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2898|
        ASRS     r0,r0,#22
        B        |L4.2992|
|L4.2898|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2910|
        ASRS     r0,r0,#22
        B        |L4.2992|
|L4.2910|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2924|
        ASRS     r0,r0,#22
        B        |L4.2992|
|L4.2924|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2940|
        MOV      r0,#0x40000
        B        |L4.2992|
|L4.2940|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2956|
        MOV      r0,#0x40000
        B        |L4.2992|
|L4.2956|
        LDR      r1,|L4.3128|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2972|
        MOV      r0,#0x40000
        B        |L4.2992|
|L4.2972|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.2988|
        MOV      r0,#0x40000
        B        |L4.2992|
|L4.2988|
        MOV      r0,#0x1000000
|L4.2992|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x88
        STR      r0,[r1,#0xc]
        B        |L4.3190|
|L4.3000|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3014|
        LDR      r0,|L4.3132|
        B        |L4.3184|
|L4.3014|
        LDR      r1,|L4.3124|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3028|
        LDR      r0,|L4.3132|
        B        |L4.3184|
|L4.3028|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3042|
        LDR      r0,|L4.3132|
        B        |L4.3184|
|L4.3042|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3056|
        LDR      r0,|L4.3132|
        B        |L4.3184|
|L4.3056|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3070|
        ASRS     r0,r0,#22
        B        |L4.3184|
|L4.3070|
        LDR      r1,|L4.3124|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3082|
        ASRS     r0,r0,#22
        B        |L4.3184|
|L4.3082|
        LDR      r1,|L4.3128|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3094|
        ASRS     r0,r0,#22
        B        |L4.3184|
|L4.3094|
        LDR      r1,|L4.3124|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3108|
        ASRS     r0,r0,#22
        B        |L4.3184|
|L4.3108|
        LDR      r1,|L4.3128|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3136|
        MOV      r0,#0x40000
        B        |L4.3184|
|L4.3124|
        DCD      0x40026428
|L4.3128|
        DCD      0x40026088
|L4.3132|
        DCD      0x00800004
|L4.3136|
        LDR      r1,|L4.4032|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3150|
        MOV      r0,#0x40000
        B        |L4.3184|
|L4.3150|
        LDR      r1,|L4.4036|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3164|
        MOV      r0,#0x40000
        B        |L4.3184|
|L4.3164|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3180|
        MOV      r0,#0x40000
        B        |L4.3184|
|L4.3180|
        MOV      r0,#0x1000000
|L4.3184|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0xa0
        STR      r0,[r1,#8]
|L4.3190|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.3384|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3214|
        LDR      r0,|L4.4040|
        B        |L4.3376|
|L4.3214|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3228|
        LDR      r0,|L4.4040|
        B        |L4.3376|
|L4.3228|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3242|
        LDR      r0,|L4.4040|
        B        |L4.3376|
|L4.3242|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3256|
        LDR      r0,|L4.4040|
        B        |L4.3376|
|L4.3256|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3270|
        MOVS     r0,#0x40
        B        |L4.3376|
|L4.3270|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3284|
        MOVS     r0,#0x40
        B        |L4.3376|
|L4.3284|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3298|
        MOVS     r0,#0x40
        B        |L4.3376|
|L4.3298|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3312|
        MOVS     r0,#0x40
        B        |L4.3376|
|L4.3312|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3328|
        MOV      r0,#0x10000
        B        |L4.3376|
|L4.3328|
        LDR      r1,|L4.4032|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3342|
        MOV      r0,#0x10000
        B        |L4.3376|
|L4.3342|
        LDR      r1,|L4.4036|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3356|
        MOV      r0,#0x10000
        B        |L4.3376|
|L4.3356|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3372|
        MOV      r0,#0x10000
        B        |L4.3376|
|L4.3372|
        MOV      r0,#0x400000
|L4.3376|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x34
        STR      r0,[r1,#0]
        B        |L4.3954|
|L4.3384|
        LDR      r1,|L4.4036|
        ADDS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.3578|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3408|
        LDR      r0,|L4.4040|
        B        |L4.3570|
|L4.3408|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3422|
        LDR      r0,|L4.4040|
        B        |L4.3570|
|L4.3422|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3436|
        LDR      r0,|L4.4040|
        B        |L4.3570|
|L4.3436|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3450|
        LDR      r0,|L4.4040|
        B        |L4.3570|
|L4.3450|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3464|
        MOVS     r0,#0x40
        B        |L4.3570|
|L4.3464|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3478|
        MOVS     r0,#0x40
        B        |L4.3570|
|L4.3478|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3492|
        MOVS     r0,#0x40
        B        |L4.3570|
|L4.3492|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3506|
        MOVS     r0,#0x40
        B        |L4.3570|
|L4.3506|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3522|
        MOV      r0,#0x10000
        B        |L4.3570|
|L4.3522|
        LDR      r1,|L4.4032|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3536|
        MOV      r0,#0x10000
        B        |L4.3570|
|L4.3536|
        LDR      r1,|L4.4036|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3550|
        MOV      r0,#0x10000
        B        |L4.3570|
|L4.3550|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3566|
        MOV      r0,#0x10000
        B        |L4.3570|
|L4.3566|
        MOV      r0,#0x400000
|L4.3570|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x38
        STR      r0,[r1,#0]
        B        |L4.3954|
|L4.3578|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BLS      |L4.3772|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3602|
        LDR      r0,|L4.4040|
        B        |L4.3764|
|L4.3602|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3616|
        LDR      r0,|L4.4040|
        B        |L4.3764|
|L4.3616|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3630|
        LDR      r0,|L4.4040|
        B        |L4.3764|
|L4.3630|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3644|
        LDR      r0,|L4.4040|
        B        |L4.3764|
|L4.3644|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3658|
        MOVS     r0,#0x40
        B        |L4.3764|
|L4.3658|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3672|
        MOVS     r0,#0x40
        B        |L4.3764|
|L4.3672|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3686|
        MOVS     r0,#0x40
        B        |L4.3764|
|L4.3686|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3700|
        MOVS     r0,#0x40
        B        |L4.3764|
|L4.3700|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3716|
        MOV      r0,#0x10000
        B        |L4.3764|
|L4.3716|
        LDR      r1,|L4.4032|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3730|
        MOV      r0,#0x10000
        B        |L4.3764|
|L4.3730|
        LDR      r1,|L4.4036|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3744|
        MOV      r0,#0x10000
        B        |L4.3764|
|L4.3744|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3760|
        MOV      r0,#0x10000
        B        |L4.3764|
|L4.3760|
        MOV      r0,#0x400000
|L4.3764|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0xa0
        STR      r0,[r1,#0xc]
        B        |L4.3954|
|L4.3772|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x90
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3786|
        LDR      r0,|L4.4040|
        B        |L4.3948|
|L4.3786|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3800|
        LDR      r0,|L4.4040|
        B        |L4.3948|
|L4.3800|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3814|
        LDR      r0,|L4.4040|
        B        |L4.3948|
|L4.3814|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x30
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3828|
        LDR      r0,|L4.4040|
        B        |L4.3948|
|L4.3828|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x78
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3842|
        MOVS     r0,#0x40
        B        |L4.3948|
|L4.3842|
        LDR      r1,|L4.4032|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3856|
        MOVS     r0,#0x40
        B        |L4.3948|
|L4.3856|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x18
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3870|
        MOVS     r0,#0x40
        B        |L4.3948|
|L4.3870|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x48
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3884|
        MOVS     r0,#0x40
        B        |L4.3948|
|L4.3884|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3900|
        MOV      r0,#0x10000
        B        |L4.3948|
|L4.3900|
        LDR      r1,|L4.4032|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3914|
        MOV      r0,#0x10000
        B        |L4.3948|
|L4.3914|
        LDR      r1,|L4.4036|
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3928|
        MOV      r0,#0x10000
        B        |L4.3948|
|L4.3928|
        LDR      r1,|L4.4032|
        ADDS     r1,r1,#0x60
        LDR      r0,[r4,#0]
        CMP      r0,r1
        BNE      |L4.3944|
        MOV      r0,#0x10000
        B        |L4.3948|
|L4.3944|
        MOV      r0,#0x400000
|L4.3948|
        LDR      r1,|L4.4036|
        SUBS     r1,r1,#0xa0
        STR      r0,[r1,#8]
|L4.3954|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x16
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0x14]
        ORR      r0,r0,#0x80
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0x14]
        LDR      r0,[r4,#0x40]
        CBNZ     r0,|L4.3986|
        LDR      r0,[r4,#0x48]
        CBZ      r0,|L4.3998|
|L4.3986|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#8
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
|L4.3998|
        LDR      r0,[r4,#0]
        LDR      r0,[r0,#0]
        ORR      r0,r0,#1
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0]
        B        |L4.4026|
|L4.4012|
        NOP      
        MOVS     r0,#0
        STRB     r0,[r4,#0x34]
        NOP      
        MOV      r9,#2
|L4.4026|
        MOV      r0,r9
        B        |L4.32|
        ENDP

|L4.4032|
        DCD      0x40026440
|L4.4036|
        DCD      0x400260a0
|L4.4040|
        DCD      0x00800001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REVSH|
#line 402
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____RRX|
#line 587
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_DMAEx_ChangeMemory [CODE]
        EXPORT HAL_DMAEx_MultiBufferStart [CODE]
        EXPORT HAL_DMAEx_MultiBufferStart_IT [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP DMA_MultiBufferSetConfig

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
