; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\stm32f7xx_hal_flash_ex.o --depend=cnn_1\stm32f7xx_hal_flash_ex.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O0 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\stm32f7xx_hal_flash_ex.crf ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.FLASH_Erase_Sector||, CODE, READONLY, ALIGN=2

FLASH_Erase_Sector PROC
        PUSH     {r4,lr}
        MOVS     r2,#0
        CBNZ     r1,|L1.8|
        B        |L1.28|
|L1.8|
        CMP      r1,#1
        BNE      |L1.16|
        LSLS     r2,r1,#8
        B        |L1.28|
|L1.16|
        CMP      r1,#2
        BNE      |L1.24|
        LSLS     r2,r1,#8
        B        |L1.28|
|L1.24|
        MOV      r2,#0x300
|L1.28|
        LDR      r3,|L1.116|
        LDR      r3,[r3,#0]
        BIC      r3,r3,#0x300
        LDR      r4,|L1.116|
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#0]
        ORRS     r3,r3,r2
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#0]
        BIC      r3,r3,#0xf8
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#0]
        MOVS     r4,#0x78
        RBIT     r4,r4
        CLZ      r4,r4
        LSL      r4,r0,r4
        ORR      r4,r4,#2
        ORRS     r3,r3,r4
        LDR      r4,|L1.116|
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#0]
        ORR      r3,r3,#0x10000
        STR      r3,[r4,#0]
        NOP      
        NOP      
        NOP      
        DSB      
        NOP      
        NOP      
        NOP      
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.116|
        DCD      0x40023c10

        AREA ||i.FLASH_MassErase||, CODE, READONLY, ALIGN=2

FLASH_MassErase PROC
        LDR      r1,|L2.60|
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x300
        LDR      r2,|L2.60|
        STR      r1,[r2,#0]
        MOV      r1,r2
        LDR      r1,[r1,#0]
        ORR      r1,r1,#4
        STR      r1,[r2,#0]
        MOV      r1,r2
        LDR      r1,[r1,#0]
        MOV      r2,#0x10000
        ORR      r2,r2,r0,LSL #8
        ORRS     r1,r1,r2
        LDR      r2,|L2.60|
        STR      r1,[r2,#0]
        NOP      
        NOP      
        NOP      
        DSB      
        NOP      
        NOP      
        NOP      
        BX       lr
        ENDP

        DCW      0x0000
|L2.60|
        DCD      0x40023c10

        AREA ||i.FLASH_OB_BOR_LevelConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_BOR_LevelConfig PROC
        MOV      r1,r0
        LDR      r0,|L3.20|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0xc
        ORRS     r0,r0,r1
        LDR      r2,|L3.20|
        STR      r0,[r2,#0]
        MOVS     r0,#0
        BX       lr
        ENDP

|L3.20|
        DCD      0x40023c14

        AREA ||i.FLASH_OB_BootAddressConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_BootAddressConfig PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOVS     r6,#0
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r6,r0
        CBNZ     r6,|L4.52|
        CMP      r5,#0x10
        BNE      |L4.40|
        LDR      r0,|L4.56|
        LDR      r0,[r0,#0]
        BFC      r0,#0,#16
        ORRS     r0,r0,r4
        LDR      r1,|L4.56|
        STR      r0,[r1,#0]
        B        |L4.52|
|L4.40|
        LDR      r0,|L4.56|
        LDR      r0,[r0,#0]
        BFI      r0,r4,#16,#16
        LDR      r1,|L4.56|
        STR      r0,[r1,#0]
|L4.52|
        MOV      r0,r6
        POP      {r4-r6,pc}
        ENDP

|L4.56|
        DCD      0x40023c18

        AREA ||i.FLASH_OB_DisableWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_DisableWRP PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
        CBNZ     r5,|L5.28|
        LDR      r0,|L5.32|
        LDR      r0,[r0,#0]
        ORRS     r0,r0,r4
        LDR      r1,|L5.32|
        STR      r0,[r1,#0]
|L5.28|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

|L5.32|
        DCD      0x40023c14

        AREA ||i.FLASH_OB_EnableWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_EnableWRP PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
        CBNZ     r5,|L6.28|
        LDR      r0,|L6.32|
        LDR      r0,[r0,#0]
        BICS     r0,r0,r4
        LDR      r1,|L6.32|
        STR      r0,[r1,#0]
|L6.28|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

|L6.32|
        DCD      0x40023c14

        AREA ||i.FLASH_OB_GetBOR||, CODE, READONLY, ALIGN=2

FLASH_OB_GetBOR PROC
        LDR      r0,|L7.12|
        LDR      r0,[r0,#0]
        AND      r0,r0,#0xc
        BX       lr
        ENDP

        DCW      0x0000
|L7.12|
        DCD      0x40023c14

        AREA ||i.FLASH_OB_GetBootAddress||, CODE, READONLY, ALIGN=2

FLASH_OB_GetBootAddress PROC
        MOV      r1,r0
        MOVS     r0,#0
        CMP      r1,#0x10
        BNE      |L8.16|
        LDR      r2,|L8.24|
        LDR      r2,[r2,#0]
        UXTH     r0,r2
        B        |L8.22|
|L8.16|
        LDR      r2,|L8.24|
        LDR      r2,[r2,#0]
        LSRS     r0,r2,#16
|L8.22|
        BX       lr
        ENDP

|L8.24|
        DCD      0x40023c18

        AREA ||i.FLASH_OB_GetRDP||, CODE, READONLY, ALIGN=2

FLASH_OB_GetRDP PROC
        MOVS     r0,#0xaa
        LDR      r1,|L9.28|
        LDRB     r1,[r1,#0]
        CMP      r1,#0xaa
        BNE      |L9.12|
        B        |L9.26|
|L9.12|
        LDR      r1,|L9.28|
        LDRB     r1,[r1,#0]
        CMP      r1,#0xcc
        BNE      |L9.24|
        MOVS     r0,#0xcc
        B        |L9.26|
|L9.24|
        MOVS     r0,#0x55
|L9.26|
        BX       lr
        ENDP

|L9.28|
        DCD      0x40023c15

        AREA ||i.FLASH_OB_GetUser||, CODE, READONLY, ALIGN=2

FLASH_OB_GetUser PROC
        LDR      r0,|L10.12|
        LDR      r0,[r0,#0]
        LDR      r1,|L10.16|
        ANDS     r0,r0,r1
        BX       lr
        ENDP

        DCW      0x0000
|L10.12|
        DCD      0x40023c14
|L10.16|
        DCD      0xc00000f0

        AREA ||i.FLASH_OB_GetWRP||, CODE, READONLY, ALIGN=2

FLASH_OB_GetWRP PROC
        LDR      r0,|L11.12|
        LDR      r0,[r0,#0]
        AND      r0,r0,#0xff0000
        BX       lr
        ENDP

        DCW      0x0000
|L11.12|
        DCD      0x40023c14

        AREA ||i.FLASH_OB_RDP_LevelConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_RDP_LevelConfig PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r5,r0
        CBNZ     r5,|L12.22|
        LDR      r0,|L12.28|
        STRB     r4,[r0,#0]
|L12.22|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L12.28|
        DCD      0x40023c15

        AREA ||i.FLASH_OB_UserConfig||, CODE, READONLY, ALIGN=2

FLASH_OB_UserConfig PROC
        PUSH     {r3-r11,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r7,r3
        LDRD     r9,r10,[sp,#0x28]
        MOV      r11,#0
        MOVS     r0,#0
        STR      r0,[sp,#0]
        MOV      r8,r0
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r8,r0
        CMP      r8,#0
        BNE      |L13.80|
        LDR      r11,|L13.88|
        ORR      r0,r5,r4
        ORRS     r0,r0,r6
        ORRS     r0,r0,r7
        ORR      r0,r0,r9
        ORR      r0,r0,r10
        STR      r0,[sp,#0]
        LDR      r0,|L13.92|
        LDR      r0,[r0,#0]
        BIC      r0,r0,r11
        LDR      r1,[sp,#0]
        ORRS     r0,r0,r1
        LDR      r1,|L13.92|
        STR      r0,[r1,#0]
|L13.80|
        MOV      r0,r8
        POP      {r3-r11,pc}
        ENDP

        DCW      0x0000
|L13.88|
        DCD      0xc00000f0
|L13.92|
        DCD      0x40023c14

        AREA ||i.HAL_FLASHEx_Erase||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_Erase PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r6,r1
        MOVS     r7,#1
        MOVS     r5,#0
        NOP      
        LDR      r0,|L14.160|
        LDRB     r0,[r0,#0x14]  ; pFlash
        CMP      r0,#1
        BNE      |L14.28|
        MOVS     r0,#2
|L14.24|
        POP      {r4-r8,pc}
|L14.28|
        MOVS     r0,#1
        LDR      r1,|L14.160|
        STRB     r0,[r1,#0x14]
        NOP      
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r7,r0
        CBNZ     r7,|L14.144|
        MOV      r0,#0xffffffff
        STR      r0,[r6,#0]
        LDR      r0,[r4,#0]
        CMP      r0,#1
        BNE      |L14.90|
        LDRB     r0,[r4,#0xc]
        BL       FLASH_MassErase
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r7,r0
        LDR      r0,|L14.164|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#4
        LDR      r1,|L14.164|
        STR      r0,[r1,#0]
        B        |L14.144|
|L14.90|
        LDR      r5,[r4,#4]
        B        |L14.132|
|L14.94|
        LDRB     r1,[r4,#0xc]
        MOV      r0,r5
        BL       FLASH_Erase_Sector
        MOV      r0,#0xc350
        BL       FLASH_WaitForLastOperation
        MOV      r7,r0
        LDR      r0,|L14.164|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x7a
        LDR      r1,|L14.164|
        STR      r0,[r1,#0]
        CBZ      r7,|L14.130|
        STR      r5,[r6,#0]
        B        |L14.142|
|L14.130|
        ADDS     r5,r5,#1
|L14.132|
        LDRD     r1,r0,[r4,#4]
        ADD      r0,r0,r1
        CMP      r0,r5
        BHI      |L14.94|
|L14.142|
        NOP      
|L14.144|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L14.160|
        STRB     r0,[r1,#0x14]
        NOP      
        MOV      r0,r7
        B        |L14.24|
        ENDP

        DCW      0x0000
|L14.160|
        DCD      pFlash
|L14.164|
        DCD      0x40023c10

        AREA ||i.HAL_FLASHEx_Erase_IT||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_Erase_IT PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        NOP      
        LDR      r0,|L15.108|
        LDRB     r0,[r0,#0x14]  ; pFlash
        CMP      r0,#1
        BNE      |L15.20|
        MOVS     r0,#2
|L15.18|
        POP      {r4-r6,pc}
|L15.20|
        MOVS     r0,#1
        LDR      r1,|L15.108|
        STRB     r0,[r1,#0x14]
        NOP      
        LDR      r0,|L15.112|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L15.112|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x2000000
        STR      r0,[r1,#0]
        MOVS     r0,#0xf3
        SUBS     r1,r1,#4
        STR      r0,[r1,#0]
        LDR      r0,[r4,#0]
        CMP      r0,#1
        BNE      |L15.76|
        MOVS     r0,#2
        LDR      r1,|L15.108|
        STRB     r0,[r1,#0]
        LDRB     r0,[r4,#0xc]
        BL       FLASH_MassErase
        B        |L15.102|
|L15.76|
        MOVS     r0,#1
        LDR      r1,|L15.108|
        STRB     r0,[r1,#0]
        LDR      r0,[r4,#8]
        STR      r0,[r1,#4]  ; pFlash
        LDR      r0,[r4,#4]
        STR      r0,[r1,#0xc]  ; pFlash
        LDRB     r0,[r4,#0xc]
        STRB     r0,[r1,#8]
        LDRB     r1,[r4,#0xc]
        LDR      r0,[r4,#4]
        BL       FLASH_Erase_Sector
|L15.102|
        MOV      r0,r5
        B        |L15.18|
        ENDP

        DCW      0x0000
|L15.108|
        DCD      pFlash
|L15.112|
        DCD      0x40023c10

        AREA ||i.HAL_FLASHEx_OBGetConfig||, CODE, READONLY, ALIGN=1

HAL_FLASHEx_OBGetConfig PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOVS     r0,#0x3f
        STR      r0,[r4,#0]
        BL       FLASH_OB_GetWRP
        STR      r0,[r4,#8]
        BL       FLASH_OB_GetRDP
        STR      r0,[r4,#0xc]
        BL       FLASH_OB_GetUser
        STR      r0,[r4,#0x14]
        BL       FLASH_OB_GetBOR
        STR      r0,[r4,#0x10]
        MOVS     r0,#0x10
        BL       FLASH_OB_GetBootAddress
        STR      r0,[r4,#0x18]
        MOVS     r0,#0x20
        BL       FLASH_OB_GetBootAddress
        STR      r0,[r4,#0x1c]
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_FLASHEx_OBProgram||, CODE, READONLY, ALIGN=2

HAL_FLASHEx_OBProgram PROC
        PUSH     {r2-r6,lr}
        MOV      r4,r0
        MOVS     r5,#1
        NOP      
        LDR      r0,|L17.196|
        LDRB     r0,[r0,#0x14]  ; pFlash
        CMP      r0,#1
        BNE      |L17.20|
        MOVS     r0,#2
|L17.18|
        POP      {r2-r6,pc}
|L17.20|
        MOVS     r0,#1
        LDR      r1,|L17.196|
        STRB     r0,[r1,#0x14]
        NOP      
        LDRB     r0,[r4,#0]
        AND      r0,r0,#1
        CBZ      r0,|L17.60|
        LDR      r0,[r4,#4]
        CMP      r0,#1
        BNE      |L17.52|
        LDR      r0,[r4,#8]
        BL       FLASH_OB_EnableWRP
        MOV      r5,r0
        B        |L17.60|
|L17.52|
        LDR      r0,[r4,#8]
        BL       FLASH_OB_DisableWRP
        MOV      r5,r0
|L17.60|
        LDRB     r0,[r4,#0]
        AND      r0,r0,#2
        CMP      r0,#2
        BNE      |L17.78|
        LDRB     r0,[r4,#0xc]
        BL       FLASH_OB_RDP_LevelConfig
        MOV      r5,r0
|L17.78|
        LDRB     r0,[r4,#0]
        AND      r0,r0,#4
        CMP      r0,#4
        BNE      |L17.128|
        LDR      r0,[r4,#0x14]
        AND      r0,r0,#0x40000000
        LDR      r1,[r4,#0x14]
        AND      r1,r1,#0x80000000
        STRD     r1,r0,[sp,#0]
        LDRB     r6,[r4,#0x14]
        AND      r3,r6,#0x80
        AND      r2,r6,#0x40
        AND      r1,r6,#0x20
        AND      r0,r6,#0x10
        BL       FLASH_OB_UserConfig
        MOV      r5,r0
|L17.128|
        LDRB     r0,[r4,#0]
        AND      r0,r0,#8
        CMP      r0,#8
        BNE      |L17.146|
        LDRB     r0,[r4,#0x10]
        BL       FLASH_OB_BOR_LevelConfig
        MOV      r5,r0
|L17.146|
        LDRB     r0,[r4,#0]
        AND      r0,r0,#0x10
        CMP      r0,#0x10
        BNE      |L17.164|
        LDR      r1,[r4,#0x18]
        BL       FLASH_OB_BootAddressConfig
        MOV      r5,r0
|L17.164|
        LDRB     r0,[r4,#0]
        AND      r0,r0,#0x20
        CMP      r0,#0x20
        BNE      |L17.182|
        LDR      r1,[r4,#0x1c]
        BL       FLASH_OB_BootAddressConfig
        MOV      r5,r0
|L17.182|
        NOP      
        MOVS     r0,#0
        LDR      r1,|L17.196|
        STRB     r0,[r1,#0x14]
        NOP      
        MOV      r0,r5
        B        |L17.18|
        ENDP

|L17.196|
        DCD      pFlash

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____REVSH|
#line 402
|__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____RRX|
#line 587
|__asm___24_stm32f7xx_hal_flash_ex_c_6648b60e____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT FLASH_Erase_Sector [CODE]
        EXPORT HAL_FLASHEx_Erase [CODE]
        EXPORT HAL_FLASHEx_Erase_IT [CODE]
        EXPORT HAL_FLASHEx_OBGetConfig [CODE]
        EXPORT HAL_FLASHEx_OBProgram [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT FLASH_WaitForLastOperation [CODE]
        IMPORT pFlash [DATA]

        KEEP FLASH_MassErase
        KEEP FLASH_OB_BOR_LevelConfig
        KEEP FLASH_OB_BootAddressConfig
        KEEP FLASH_OB_DisableWRP
        KEEP FLASH_OB_EnableWRP
        KEEP FLASH_OB_GetBOR
        KEEP FLASH_OB_GetBootAddress
        KEEP FLASH_OB_GetRDP
        KEEP FLASH_OB_GetUser
        KEEP FLASH_OB_GetWRP
        KEEP FLASH_OB_RDP_LevelConfig
        KEEP FLASH_OB_UserConfig

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
