; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\stm32f7xx_hal_gpio.o --depend=cnn_1\stm32f7xx_hal_gpio.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O3 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\stm32f7xx_hal_gpio.crf ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.HAL_GPIO_DeInit||, CODE, READONLY, ALIGN=2

HAL_GPIO_DeInit PROC
        PUSH     {r4-r11,lr}
        LDR      lr,|L1.292|
        MOV      r9,r1
        MOVS     r1,#0
        MOV      r10,#1
        MOV      r11,#0xf
|L1.20|
        LSL      r4,r10,r1
        AND      r3,r9,r4
        CMP      r3,r4
        BNE      |L1.280|
        LDR      r7,[r0,#0]
        MOVS     r5,#3
        LSLS     r6,r1,#1
        LSRS     r2,r1,#3
        LSLS     r5,r5,r6
        BICS     r7,r7,r5
        STR      r7,[r0,#0]
        LSLS     r6,r1,#29
        ADD      r2,r0,r2,LSL #2
        LDR      r12,[r2,#0x20]
        LSR      r8,r6,#27
        LSL      r7,r11,r8
        BIC      r12,r12,r7
        STR      r12,[r2,#0x20]
        LSLS     r7,r1,#30
        BIC      r8,r1,#3
        LDR      r12,[r0,#8]
        LSRS     r7,r7,#28
        ADD      r6,r8,lr
        LDR      r8,|L1.296|
        LSL      r2,r11,r7
        BIC      r12,r12,r5
        STR      r12,[r0,#8]
        LDR      r12,[r0,#4]
        CMP      r0,r8
        BIC      r12,r12,r4
        STR      r12,[r0,#4]
        LDR      r4,[r0,#0xc]
        BIC      r4,r4,r5
        STR      r4,[r0,#0xc]
        LDR      r4,[r6,#0x808]
        AND      r4,r2,r4
        BNE      |L1.140|
        MOVS     r5,#0
        B        |L1.232|
|L1.140|
        LDR      r5,|L1.300|
        CMP      r0,r5
        BNE      |L1.150|
        MOVS     r5,#1
        B        |L1.232|
|L1.150|
        LDR      r5,|L1.304|
        CMP      r0,r5
        BNE      |L1.160|
        MOVS     r5,#2
        B        |L1.232|
|L1.160|
        LDR      r5,|L1.308|
        CMP      r0,r5
        BNE      |L1.170|
        MOVS     r5,#3
        B        |L1.232|
|L1.170|
        LDR      r5,|L1.312|
        CMP      r0,r5
        BNE      |L1.180|
        MOVS     r5,#4
        B        |L1.232|
|L1.180|
        LDR      r5,|L1.316|
        CMP      r0,r5
        BNE      |L1.190|
        MOVS     r5,#5
        B        |L1.232|
|L1.190|
        LDR      r5,|L1.320|
        CMP      r0,r5
        BNE      |L1.200|
        MOVS     r5,#6
        B        |L1.232|
|L1.200|
        LDR      r5,|L1.324|
        CMP      r0,r5
        BNE      |L1.210|
        MOVS     r5,#7
        B        |L1.232|
|L1.210|
        LDR      r5,|L1.328|
        CMP      r0,r5
        BNE      |L1.220|
        MOVS     r5,#8
        B        |L1.232|
|L1.220|
        LDR      r5,|L1.332|
        CMP      r0,r5
        BNE      |L1.230|
        MOVS     r5,#9
        B        |L1.232|
|L1.230|
        MOVS     r5,#0xa
|L1.232|
        LSLS     r5,r5,r7
        CMP      r5,r4
        BNE      |L1.280|
        LDR      r5,[r6,#0x808]
        LDR      r4,|L1.336|
        ADDS     r7,r4,#4
        BICS     r5,r5,r2
        STR      r5,[r6,#0x808]
        LDR      r6,[r4,#0]
        ADDS     r2,r7,#4
        ADDS     r5,r2,#4
        BICS     r6,r6,r3
        STR      r6,[r4,#0]
        LDR      r4,[r7,#0]
        BICS     r4,r4,r3
        STR      r4,[r7,#0]
        LDR      r4,[r2,#0]
        BICS     r4,r4,r3
        STR      r4,[r2,#0]
        LDR      r2,[r5,#0]
        BICS     r2,r2,r3
        STR      r2,[r5,#0]
|L1.280|
        ADDS     r1,r1,#1
        CMP      r1,#0x10
        BCC      |L1.20|
        POP      {r4-r11,pc}
        ENDP

|L1.292|
        DCD      0x40013000
|L1.296|
        DCD      0x40020000
|L1.300|
        DCD      0x40020400
|L1.304|
        DCD      0x40020800
|L1.308|
        DCD      0x40020c00
|L1.312|
        DCD      0x40021000
|L1.316|
        DCD      0x40021400
|L1.320|
        DCD      0x40021800
|L1.324|
        DCD      0x40021c00
|L1.328|
        DCD      0x40022000
|L1.332|
        DCD      0x40022400
|L1.336|
        DCD      0x40013c00

        AREA ||i.HAL_GPIO_EXTI_Callback||, CODE, READONLY, ALIGN=1

HAL_GPIO_EXTI_Callback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_GPIO_EXTI_IRQHandler||, CODE, READONLY, ALIGN=2

HAL_GPIO_EXTI_IRQHandler PROC
        LDR      r1,|L3.20|
        PUSH     {r4,lr}
        LDR      r2,[r1,#0]
        TST      r2,r0
        BEQ      |L3.16|
        STR      r0,[r1,#0]
        BL       HAL_GPIO_EXTI_Callback
|L3.16|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L3.20|
        DCD      0x40013c14

        AREA ||i.HAL_GPIO_Init||, CODE, READONLY, ALIGN=2

HAL_GPIO_Init PROC
        PUSH     {r3-r11,lr}
        LDR      lr,|L4.420|
        MOVS     r2,#0
        MOV      r8,#1
        MOV      r11,#3
        MOV      r10,#0xf
        NOP      
|L4.24|
        LDR      r3,[r1,#0]
        LSL      r4,r8,r2
        ANDS     r3,r3,r4
        CMP      r3,r4
        BNE      |L4.264|
        LDR      r5,[r1,#4]
        CMP      r5,#2
        BEQ      |L4.46|
        CMP      r5,#0x12
        BNE      |L4.78|
|L4.46|
        LSRS     r5,r2,#3
        LDR      r6,[r1,#0x10]
        LSLS     r7,r2,#29
        ADD      r5,r0,r5,LSL #2
        MOV      r9,r5
        LDR      r5,[r5,#0x20]
        LSRS     r7,r7,#27
        LSL      r12,r10,r7
        LSLS     r6,r6,r7
        BIC      r5,r5,r12
        ORRS     r6,r6,r5
        STR      r6,[r9,#0x20]
|L4.78|
        LDRB     r7,[r1,#4]
        LSLS     r5,r2,#1
        LDR      r6,[r0,#0]
        LSL      r12,r11,r5
        AND      r7,r7,#3
        BIC      r6,r6,r12
        LSLS     r7,r7,r5
        ORRS     r7,r7,r6
        STR      r7,[r0,#0]
        LDR      r6,[r1,#4]
        CMP      r6,#1
        BEQ      |L4.120|
        CMP      r6,#2
        BEQ      |L4.120|
        CMP      r6,#0x11
        BEQ      |L4.120|
        CMP      r6,#0x12
        BNE      |L4.150|
|L4.120|
        LDR      r6,[r0,#8]
        LDR      r7,[r1,#0xc]
        BIC      r6,r6,r12
        LSLS     r7,r7,r5
        ORRS     r7,r7,r6
        STR      r7,[r0,#8]
        LDR      r6,[r0,#4]
        LDRB     r7,[r1,#4]
        BICS     r6,r6,r4
        UBFX     r7,r7,#4,#1
        LSLS     r7,r7,r2
        ORRS     r7,r7,r6
        STR      r7,[r0,#4]
|L4.150|
        LDR      r4,[r0,#0xc]
        LDR      r6,[r1,#8]
        BIC      r4,r4,r12
        LSLS     r6,r6,r5
        ORRS     r6,r6,r4
        STR      r6,[r0,#0xc]
        LDR      r4,[r1,#4]
        LSLS     r4,r4,#3
        BPL      |L4.406|
        LDR      r4,|L4.424|
        LDR      r5,[r4,#0]
        ORR      r5,r5,#0x4000
        STR      r5,[r4,#0]
        LDR      r4,[r4,#0]
        BIC      r6,r2,#3
        LSLS     r5,r2,#30
        AND      r4,r4,#0x4000
        STR      r4,[sp,#0]
        LDR      r4,|L4.428|
        LSRS     r5,r5,#28
        ADD      r6,r6,r4
        LDR      r4,[r6,#0x808]
        LDR      r12,|L4.432|
        LSL      r7,r10,r5
        CMP      r0,r12
        BIC      r4,r4,r7
        BNE      |L4.224|
        MOVS     r7,#0
        B        |L4.318|
|L4.224|
        LDR      r7,|L4.436|
        CMP      r0,r7
        BNE      |L4.234|
        MOVS     r7,#1
        B        |L4.318|
|L4.234|
        LDR      r7,|L4.440|
        CMP      r0,r7
        BNE      |L4.244|
        MOVS     r7,#2
        B        |L4.318|
|L4.244|
        LDR      r7,|L4.444|
        CMP      r0,r7
        BNE      |L4.254|
        MOVS     r7,#3
        B        |L4.318|
|L4.254|
        LDR      r7,|L4.448|
        CMP      r0,r7
        BNE      |L4.266|
        MOVS     r7,#4
        B        |L4.318|
|L4.264|
        B        |L4.406|
|L4.266|
        LDR      r7,|L4.452|
        CMP      r0,r7
        BNE      |L4.276|
        MOVS     r7,#5
        B        |L4.318|
|L4.276|
        LDR      r7,|L4.456|
        CMP      r0,r7
        BNE      |L4.286|
        MOVS     r7,#6
        B        |L4.318|
|L4.286|
        LDR      r7,|L4.460|
        CMP      r0,r7
        BNE      |L4.296|
        MOVS     r7,#7
        B        |L4.318|
|L4.296|
        LDR      r7,|L4.464|
        CMP      r0,r7
        BNE      |L4.306|
        MOVS     r7,#8
        B        |L4.318|
|L4.306|
        LDR      r7,|L4.468|
        CMP      r0,r7
        BNE      |L4.316|
        MOVS     r7,#9
        B        |L4.318|
|L4.316|
        MOVS     r7,#0xa
|L4.318|
        LSLS     r7,r7,r5
        ORRS     r7,r7,r4
        MOV      r5,lr
        STR      r7,[r6,#0x808]
        LDR      r6,[r1,#4]
        LDR      r4,[lr,#0]
        LSLS     r6,r6,#15
        BIC      r4,r4,r3
        BPL      |L4.344|
        ORRS     r4,r4,r3
|L4.344|
        LDR      r6,|L4.420|
        STR      r4,[r5,#0]
        ADDS     r6,r6,#4
        LDR      r5,[r1,#4]
        LDR      r4,[r6,#0]
        LSLS     r5,r5,#14
        BIC      r4,r4,r3
        BPL      |L4.364|
        ORRS     r4,r4,r3
|L4.364|
        LDR      r7,|L4.420|
        STR      r4,[r6,#0]
        ADDS     r7,r7,#8
        LDR      r5,[r1,#4]
        LDR      r4,[r7,#0]
        LSLS     r5,r5,#11
        BIC      r4,r4,r3
        BPL      |L4.384|
        ORRS     r4,r4,r3
|L4.384|
        LDR      r5,|L4.420|
        STR      r4,[r7,#0]
        ADDS     r5,r5,#0xc
        LDR      r6,[r1,#4]
        LDR      r4,[r5,#0]
        LSLS     r6,r6,#10
        BIC      r4,r4,r3
        BPL      |L4.404|
        ORRS     r4,r4,r3
|L4.404|
        STR      r4,[r5,#0]
|L4.406|
        ADDS     r2,r2,#1
        CMP      r2,#0x10
        BCC      |L4.24|
        POP      {r3-r11,pc}
        ENDP

        DCW      0x0000
|L4.420|
        DCD      0x40013c00
|L4.424|
        DCD      0x40023844
|L4.428|
        DCD      0x40013000
|L4.432|
        DCD      0x40020000
|L4.436|
        DCD      0x40020400
|L4.440|
        DCD      0x40020800
|L4.444|
        DCD      0x40020c00
|L4.448|
        DCD      0x40021000
|L4.452|
        DCD      0x40021400
|L4.456|
        DCD      0x40021800
|L4.460|
        DCD      0x40021c00
|L4.464|
        DCD      0x40022000
|L4.468|
        DCD      0x40022400

        AREA ||i.HAL_GPIO_LockPin||, CODE, READONLY, ALIGN=1

HAL_GPIO_LockPin PROC
        PUSH     {r3,lr}
        ORR      r2,r1,#0x10000
        STR      r2,[sp,#0]
        STR      r2,[r0,#0x1c]
        STR      r1,[r0,#0x1c]
        LDR      r1,[sp,#0]
        STR      r1,[r0,#0x1c]
        LDR      r1,[r0,#0x1c]
        STR      r1,[sp,#0]
        LDR      r0,[r0,#0x1c]
        LSLS     r0,r0,#15
        BPL      |L5.30|
        MOVS     r0,#0
        POP      {r3,pc}
|L5.30|
        MOVS     r0,#1
        POP      {r3,pc}
        ENDP


        AREA ||i.HAL_GPIO_ReadPin||, CODE, READONLY, ALIGN=1

HAL_GPIO_ReadPin PROC
        LDR      r0,[r0,#0x10]
        ANDS     r0,r0,r1
        BEQ      |L6.8|
        MOVS     r0,#1
|L6.8|
        BX       lr
        ENDP


        AREA ||i.HAL_GPIO_TogglePin||, CODE, READONLY, ALIGN=1

HAL_GPIO_TogglePin PROC
        LDR      r2,[r0,#0x14]
        EORS     r2,r2,r1
        STR      r2,[r0,#0x14]
        BX       lr
        ENDP


        AREA ||i.HAL_GPIO_WritePin||, CODE, READONLY, ALIGN=1

HAL_GPIO_WritePin PROC
        CBZ      r2,|L8.6|
|L8.2|
        STR      r1,[r0,#0x18]
        BX       lr
|L8.6|
        LSLS     r1,r1,#16
        B        |L8.2|
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___20_stm32f7xx_hal_gpio_c_ea787061____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___20_stm32f7xx_hal_gpio_c_ea787061____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___20_stm32f7xx_hal_gpio_c_ea787061____REVSH|
#line 402
|__asm___20_stm32f7xx_hal_gpio_c_ea787061____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___20_stm32f7xx_hal_gpio_c_ea787061____RRX|
#line 587
|__asm___20_stm32f7xx_hal_gpio_c_ea787061____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_GPIO_DeInit [CODE]
        EXPORT HAL_GPIO_EXTI_Callback [CODE,WEAK]
        EXPORT HAL_GPIO_EXTI_IRQHandler [CODE]
        EXPORT HAL_GPIO_Init [CODE]
        EXPORT HAL_GPIO_LockPin [CODE]
        EXPORT HAL_GPIO_ReadPin [CODE]
        EXPORT HAL_GPIO_TogglePin [CODE]
        EXPORT HAL_GPIO_WritePin [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
