; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\stm32f7xx_hal_dma_ex.o --depend=cnn_1\stm32f7xx_hal_dma_ex.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O3 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\stm32f7xx_hal_dma_ex.crf ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.DMA_MultiBufferSetConfig||, CODE, READONLY, ALIGN=1

DMA_MultiBufferSetConfig PROC
        PUSH     {r4,lr}
        LDR      r4,[r0,#0]
        STR      r3,[r4,#4]
        LDR      r3,[r0,#8]
        CMP      r3,#0x40
        LDR      r3,[r0,#0]
        BEQ      |L1.22|
        STR      r1,[r3,#8]
        LDR      r0,[r0,#0]
        STR      r2,[r0,#0xc]
        POP      {r4,pc}
|L1.22|
        STR      r2,[r3,#8]
        LDR      r0,[r0,#0]
        STR      r1,[r0,#0xc]
        POP      {r4,pc}
        ENDP


        AREA ||i.HAL_DMAEx_ChangeMemory||, CODE, READONLY, ALIGN=1

HAL_DMAEx_ChangeMemory PROC
        LDR      r0,[r0,#0]
        CBZ      r2,|L2.10|
        STR      r1,[r0,#0x10]
|L2.6|
        MOVS     r0,#0
        BX       lr
|L2.10|
        STR      r1,[r0,#0xc]
        B        |L2.6|
        ENDP


        AREA ||i.HAL_DMAEx_MultiBufferStart||, CODE, READONLY, ALIGN=1

HAL_DMAEx_MultiBufferStart PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        LDR      r0,[r0,#8]
        MOVS     r5,#0
        LDR      r6,[sp,#0x18]
        CMP      r0,#0x80
        BEQ      |L3.46|
        LDRB     r0,[r4,#0x34]
        CMP      r0,#1
        BEQ      |L3.56|
        LDRB     r7,[r4,#0x35]
        MOVS     r0,#1
        STRB     r0,[r4,#0x34]
        CMP      r7,#1
        BEQ      |L3.60|
        MOVS     r5,#2
|L3.40|
        MOV      r0,r5
|L3.42|
        POP      {r4-r8,pc}
|L3.46|
        MOVS     r5,#1
        MOV      r0,#0x100
        STR      r0,[r4,#0x54]
        B        |L3.40|
|L3.56|
        MOVS     r0,#2
        B        |L3.42|
|L3.60|
        MOVS     r0,#2
        STRB     r0,[r4,#0x35]
        LDR      r0,[r4,#0]
        LDR      r7,[r0,#0]
        ORR      r7,r7,#0x40000
        STR      r7,[r0,#0]
        LDR      r0,[r4,#0]
        STR      r3,[r0,#0x10]
        MOV      r3,r6
        MOV      r0,r4
        BL       DMA_MultiBufferSetConfig
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#1
        STR      r1,[r0,#0]
        B        |L3.40|
        ENDP


        AREA ||i.HAL_DMAEx_MultiBufferStart_IT||, CODE, READONLY, ALIGN=2

HAL_DMAEx_MultiBufferStart_IT PROC
        PUSH     {r3-r11,lr}
        MOV      r4,r0
        LDR      r0,[r0,#8]
        MOV      r10,#0x100
        LDR      r5,[sp,#0x28]
        CMP      r0,#0x80
        MOV      r0,#0
        STR      r0,[sp,#0]
        BEQ      |L4.62|
        LDRB     r0,[r4,#0x34]
        CMP      r0,#1
        BEQ      |L4.70|
        LDRB     r7,[r4,#0x35]
        MOVS     r6,#1
        MOVS     r0,#0
        STRB     r6,[r4,#0x34]
        CMP      r7,#1
        BEQ      |L4.74|
        MOVS     r1,#2
        STR      r1,[sp,#0]
        STRB     r0,[r4,#0x34]
|L4.56|
        LDR      r0,[sp,#0]
|L4.58|
        POP      {r3-r11,pc}
|L4.62|
        STR      r10,[r4,#0x54]
        MOVS     r0,#1
        B        |L4.58|
|L4.70|
        MOVS     r0,#2
        B        |L4.58|
|L4.74|
        MOVS     r6,#2
        STRB     r6,[r4,#0x35]
        STR      r0,[r4,#0x54]
        LDR      r0,[r4,#0]
        LDR      r6,[r0,#0]
        ORR      r6,r6,#0x40000
        STR      r6,[r0,#0]
        LDR      r0,[r4,#0]
        STR      r3,[r0,#0x10]
        MOV      r3,r5
        MOV      r0,r4
        BL       DMA_MultiBufferSetConfig
        LDR      r3,|L4.1128|
        MOV      r11,#0x800
        LDR      r5,|L4.1132|
        MOV      lr,#0x200000
        LDR      r6,|L4.1128|
        ADDS     r3,r3,#0x60
        LDR      r7,|L4.1132|
        ADDS     r5,r5,#0x60
        LDR      r8,|L4.1132|
        ADDS     r6,r6,#0x18
        LDR      r12,|L4.1128|
        ADDS     r7,r7,#0x18
        LDR      r9,|L4.1132|
        ADD      r8,r8,#0x48
        LDR      r1,[r4,#0]
        ADD      r12,r12,#0x78
        LDR      r0,|L4.1128|
        ADD      r9,r9,#0x78
        LDR      r2,|L4.1132|
        CMP      r1,r8
        BLS      |L4.268|
        CMP      r1,r0
        BEQ      |L4.178|
        CMP      r1,r2
        BEQ      |L4.178|
        CMP      r1,r3
        BEQ      |L4.178|
        CMP      r1,r5
        BNE      |L4.182|
|L4.178|
        MOVS     r1,#0x20
        B        |L4.258|
|L4.182|
        CMP      r1,r6
        BEQ      |L4.198|
        CMP      r1,r7
        BEQ      |L4.198|
        CMP      r1,r12
        BEQ      |L4.198|
        CMP      r1,r9
        BNE      |L4.202|
|L4.198|
        MOV      r1,r11
        B        |L4.258|
|L4.202|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.250|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.250|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.250|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.254|
|L4.250|
        MOV      r1,lr
        B        |L4.258|
|L4.254|
        MOV      r1,#0x8000000
|L4.258|
        LDR      r8,|L4.1132|
        SUB      r8,r8,#4
        B        |L4.384|
|L4.268|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0xa8
        CMP      r1,r8
        BLS      |L4.390|
        CMP      r1,r0
        BEQ      |L4.296|
        CMP      r1,r2
        BEQ      |L4.296|
        CMP      r1,r3
        BEQ      |L4.296|
        CMP      r1,r5
        BNE      |L4.300|
|L4.296|
        MOVS     r1,#0x20
        B        |L4.376|
|L4.300|
        CMP      r1,r6
        BEQ      |L4.316|
        CMP      r1,r7
        BEQ      |L4.316|
        CMP      r1,r12
        BEQ      |L4.316|
        CMP      r1,r9
        BNE      |L4.320|
|L4.316|
        MOV      r1,r11
        B        |L4.376|
|L4.320|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.368|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.368|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.368|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.372|
|L4.368|
        MOV      r1,lr
        B        |L4.376|
|L4.372|
        MOV      r1,#0x8000000
|L4.376|
        LDR      r8,|L4.1132|
        SUB      r8,r8,#8
|L4.384|
        STR      r1,[r8,#0]
        B        |L4.620|
|L4.390|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x48
        CMP      r1,r8
        BLS      |L4.512|
        CMP      r1,r0
        BEQ      |L4.418|
        CMP      r1,r2
        BEQ      |L4.418|
        CMP      r1,r3
        BEQ      |L4.418|
        CMP      r1,r5
        BNE      |L4.422|
|L4.418|
        MOVS     r1,#0x20
        B        |L4.498|
|L4.422|
        CMP      r1,r6
        BEQ      |L4.438|
        CMP      r1,r7
        BEQ      |L4.438|
        CMP      r1,r12
        BEQ      |L4.438|
        CMP      r1,r9
        BNE      |L4.442|
|L4.438|
        MOV      r1,r11
        B        |L4.498|
|L4.442|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.490|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.490|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.490|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.494|
|L4.490|
        MOV      r1,lr
        B        |L4.498|
|L4.494|
        MOV      r1,#0x8000000
|L4.498|
        LDR      r8,|L4.1128|
        SUB      r8,r8,#0x10
        STR      r1,[r8,#0xc]
        B        |L4.620|
|L4.512|
        CMP      r1,r0
        BEQ      |L4.528|
        CMP      r1,r2
        BEQ      |L4.528|
        CMP      r1,r3
        BEQ      |L4.528|
        CMP      r1,r5
        BNE      |L4.532|
|L4.528|
        MOVS     r1,#0x20
        B        |L4.608|
|L4.532|
        CMP      r1,r6
        BEQ      |L4.548|
        CMP      r1,r7
        BEQ      |L4.548|
        CMP      r1,r12
        BEQ      |L4.548|
        CMP      r1,r9
        BNE      |L4.552|
|L4.548|
        MOV      r1,r11
        B        |L4.608|
|L4.552|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.600|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.600|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.600|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.604|
|L4.600|
        MOV      r1,lr
        B        |L4.608|
|L4.604|
        MOV      r1,#0x8000000
|L4.608|
        LDR      r8,|L4.1128|
        SUB      r8,r8,#0x10
        STR      r1,[r8,#8]
|L4.620|
        MOV      r11,#0x400
        LDR      r8,|L4.1132|
        MOV      lr,#0x100000
        LDR      r1,[r4,#0]
        ADD      r8,r8,#0x48
        CMP      r1,r8
        BLS      |L4.748|
        CMP      r1,r0
        BEQ      |L4.658|
        CMP      r1,r2
        BEQ      |L4.658|
        CMP      r1,r3
        BEQ      |L4.658|
        CMP      r1,r5
        BNE      |L4.662|
|L4.658|
        MOVS     r1,#0x10
        B        |L4.738|
|L4.662|
        CMP      r1,r6
        BEQ      |L4.678|
        CMP      r1,r7
        BEQ      |L4.678|
        CMP      r1,r12
        BEQ      |L4.678|
        CMP      r1,r9
        BNE      |L4.682|
|L4.678|
        MOV      r1,r11
        B        |L4.738|
|L4.682|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.730|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.730|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.730|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.734|
|L4.730|
        MOV      r1,lr
        B        |L4.738|
|L4.734|
        MOV      r1,#0x4000000
|L4.738|
        LDR      r8,|L4.1132|
        SUB      r8,r8,#4
        B        |L4.864|
|L4.748|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0xa8
        CMP      r1,r8
        BLS      |L4.870|
        CMP      r1,r0
        BEQ      |L4.776|
        CMP      r1,r2
        BEQ      |L4.776|
        CMP      r1,r3
        BEQ      |L4.776|
        CMP      r1,r5
        BNE      |L4.780|
|L4.776|
        MOVS     r1,#0x10
        B        |L4.856|
|L4.780|
        CMP      r1,r6
        BEQ      |L4.796|
        CMP      r1,r7
        BEQ      |L4.796|
        CMP      r1,r12
        BEQ      |L4.796|
        CMP      r1,r9
        BNE      |L4.800|
|L4.796|
        MOV      r1,r11
        B        |L4.856|
|L4.800|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.848|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.848|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.848|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.852|
|L4.848|
        MOV      r1,lr
        B        |L4.856|
|L4.852|
        MOV      r1,#0x4000000
|L4.856|
        LDR      r8,|L4.1132|
        SUB      r8,r8,#8
|L4.864|
        STR      r1,[r8,#0]
        B        |L4.1100|
|L4.870|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x48
        CMP      r1,r8
        BLS      |L4.992|
        CMP      r1,r0
        BEQ      |L4.898|
        CMP      r1,r2
        BEQ      |L4.898|
        CMP      r1,r3
        BEQ      |L4.898|
        CMP      r1,r5
        BNE      |L4.902|
|L4.898|
        MOVS     r1,#0x10
        B        |L4.978|
|L4.902|
        CMP      r1,r6
        BEQ      |L4.918|
        CMP      r1,r7
        BEQ      |L4.918|
        CMP      r1,r12
        BEQ      |L4.918|
        CMP      r1,r9
        BNE      |L4.922|
|L4.918|
        MOV      r1,r11
        B        |L4.978|
|L4.922|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.970|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.970|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.970|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.974|
|L4.970|
        MOV      r1,lr
        B        |L4.978|
|L4.974|
        MOV      r1,#0x4000000
|L4.978|
        LDR      r8,|L4.1128|
        SUB      r8,r8,#0x10
        STR      r1,[r8,#0xc]
        B        |L4.1100|
|L4.992|
        CMP      r1,r0
        BEQ      |L4.1008|
        CMP      r1,r2
        BEQ      |L4.1008|
        CMP      r1,r3
        BEQ      |L4.1008|
        CMP      r1,r5
        BNE      |L4.1012|
|L4.1008|
        MOVS     r1,#0x10
        B        |L4.1088|
|L4.1012|
        CMP      r1,r6
        BEQ      |L4.1028|
        CMP      r1,r7
        BEQ      |L4.1028|
        CMP      r1,r12
        BEQ      |L4.1028|
        CMP      r1,r9
        BNE      |L4.1032|
|L4.1028|
        MOV      r1,r11
        B        |L4.1088|
|L4.1032|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.1080|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x30
        CMP      r1,r8
        BEQ      |L4.1080|
        LDR      r8,|L4.1128|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BEQ      |L4.1080|
        LDR      r8,|L4.1132|
        ADD      r8,r8,#0x90
        CMP      r1,r8
        BNE      |L4.1084|
|L4.1080|
        MOV      r1,lr
        B        |L4.1088|
|L4.1084|
        MOV      r1,#0x4000000
|L4.1088|
        LDR      r8,|L4.1128|
        SUB      r8,r8,#0x10
        STR      r1,[r8,#8]
|L4.1100|
        MOV      r11,#0x200
        LDR      r8,|L4.1132|
        MOV      lr,#0x80000
        LDR      r1,[r4,#0]
        ADD      r8,r8,#0x48
        CMP      r1,r8
        BLS      |L4.1230|
        CMP      r1,r0
        BEQ      |L4.1148|
        B        |L4.1136|
|L4.1128|
        DCD      0x40026010
|L4.1132|
        DCD      0x40026410
|L4.1136|
        CMP      r1,r2
        BEQ      |L4.1148|
        CMP      r1,r3
        BEQ      |L4.1148|
        CMP      r1,r5
        BNE      |L4.1152|
|L4.1148|
        MOVS     r1,#8
        B        |L4.1220|
|L4.1152|
        CMP      r1,r6
        BEQ      |L4.1168|
        CMP      r1,r7
        BEQ      |L4.1168|
        CMP      r1,r12
        BEQ      |L4.1168|
        CMP      r1,r9
        BNE      |L4.1172|
|L4.1168|
        MOV      r1,r11
        B        |L4.1220|
|L4.1172|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1212|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1212|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1212|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1216|
|L4.1212|
        MOV      r1,lr
        B        |L4.1220|
|L4.1216|
        MOV      r1,#0x2000000
|L4.1220|
        LDR      r8,|L4.2440|
        SUB      r8,r8,#0x34
        B        |L4.1338|
|L4.1230|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x78
        CMP      r1,r8
        BLS      |L4.1344|
        CMP      r1,r0
        BEQ      |L4.1258|
        CMP      r1,r2
        BEQ      |L4.1258|
        CMP      r1,r3
        BEQ      |L4.1258|
        CMP      r1,r5
        BNE      |L4.1262|
|L4.1258|
        MOVS     r1,#8
        B        |L4.1330|
|L4.1262|
        CMP      r1,r6
        BEQ      |L4.1278|
        CMP      r1,r7
        BEQ      |L4.1278|
        CMP      r1,r12
        BEQ      |L4.1278|
        CMP      r1,r9
        BNE      |L4.1282|
|L4.1278|
        MOV      r1,r11
        B        |L4.1330|
|L4.1282|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1322|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1322|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1322|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1326|
|L4.1322|
        MOV      r1,lr
        B        |L4.1330|
|L4.1326|
        MOV      r1,#0x2000000
|L4.1330|
        LDR      r8,|L4.2440|
        SUB      r8,r8,#0x38
|L4.1338|
        STR      r1,[r8,#0]
        B        |L4.1558|
|L4.1344|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x18
        CMP      r1,r8
        BLS      |L4.1458|
        CMP      r1,r0
        BEQ      |L4.1372|
        CMP      r1,r2
        BEQ      |L4.1372|
        CMP      r1,r3
        BEQ      |L4.1372|
        CMP      r1,r5
        BNE      |L4.1376|
|L4.1372|
        MOVS     r1,#8
        B        |L4.1444|
|L4.1376|
        CMP      r1,r6
        BEQ      |L4.1392|
        CMP      r1,r7
        BEQ      |L4.1392|
        CMP      r1,r12
        BEQ      |L4.1392|
        CMP      r1,r9
        BNE      |L4.1396|
|L4.1392|
        MOV      r1,r11
        B        |L4.1444|
|L4.1396|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1436|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1436|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1436|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1440|
|L4.1436|
        MOV      r1,lr
        B        |L4.1444|
|L4.1440|
        MOV      r1,#0x2000000
|L4.1444|
        LDR      r8,|L4.2436|
        SUB      r8,r8,#0x40
        STR      r1,[r8,#0xc]
        B        |L4.1558|
|L4.1458|
        CMP      r1,r0
        BEQ      |L4.1474|
        CMP      r1,r2
        BEQ      |L4.1474|
        CMP      r1,r3
        BEQ      |L4.1474|
        CMP      r1,r5
        BNE      |L4.1478|
|L4.1474|
        MOVS     r1,#8
        B        |L4.1546|
|L4.1478|
        CMP      r1,r6
        BEQ      |L4.1494|
        CMP      r1,r7
        BEQ      |L4.1494|
        CMP      r1,r12
        BEQ      |L4.1494|
        CMP      r1,r9
        BNE      |L4.1498|
|L4.1494|
        MOV      r1,r11
        B        |L4.1546|
|L4.1498|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1538|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1538|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1538|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1542|
|L4.1538|
        MOV      r1,lr
        B        |L4.1546|
|L4.1542|
        MOV      r1,#0x2000000
|L4.1546|
        LDR      r8,|L4.2436|
        SUB      r8,r8,#0x40
        STR      r1,[r8,#8]
|L4.1558|
        MOV      lr,#0x40000
        LDR      r8,|L4.2440|
        LDR      r1,[r4,#0]
        LDR      r11,|L4.2444|
        ADD      r8,r8,#0x18
        CMP      r1,r8
        BLS      |L4.1678|
        CMP      r1,r0
        BEQ      |L4.1596|
        CMP      r1,r2
        BEQ      |L4.1596|
        CMP      r1,r3
        BEQ      |L4.1596|
        CMP      r1,r5
        BNE      |L4.1600|
|L4.1596|
        MOV      r1,r11
        B        |L4.1668|
|L4.1600|
        CMP      r1,r6
        BEQ      |L4.1616|
        CMP      r1,r7
        BEQ      |L4.1616|
        CMP      r1,r12
        BEQ      |L4.1616|
        CMP      r1,r9
        BNE      |L4.1620|
|L4.1616|
        MOV      r1,r10
        B        |L4.1668|
|L4.1620|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1660|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1660|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1660|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1664|
|L4.1660|
        MOV      r1,lr
        B        |L4.1668|
|L4.1664|
        MOV      r1,#0x1000000
|L4.1668|
        LDR      r8,|L4.2440|
        SUB      r8,r8,#0x34
        B        |L4.1786|
|L4.1678|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x78
        CMP      r1,r8
        BLS      |L4.1792|
        CMP      r1,r0
        BEQ      |L4.1706|
        CMP      r1,r2
        BEQ      |L4.1706|
        CMP      r1,r3
        BEQ      |L4.1706|
        CMP      r1,r5
        BNE      |L4.1710|
|L4.1706|
        MOV      r1,r11
        B        |L4.1778|
|L4.1710|
        CMP      r1,r6
        BEQ      |L4.1726|
        CMP      r1,r7
        BEQ      |L4.1726|
        CMP      r1,r12
        BEQ      |L4.1726|
        CMP      r1,r9
        BNE      |L4.1730|
|L4.1726|
        MOV      r1,r10
        B        |L4.1778|
|L4.1730|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1770|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1770|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1770|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1774|
|L4.1770|
        MOV      r1,lr
        B        |L4.1778|
|L4.1774|
        MOV      r1,#0x1000000
|L4.1778|
        LDR      r8,|L4.2440|
        SUB      r8,r8,#0x38
|L4.1786|
        STR      r1,[r8,#0]
        B        |L4.2006|
|L4.1792|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x18
        CMP      r1,r8
        BLS      |L4.1906|
        CMP      r1,r0
        BEQ      |L4.1820|
        CMP      r1,r2
        BEQ      |L4.1820|
        CMP      r1,r3
        BEQ      |L4.1820|
        CMP      r1,r5
        BNE      |L4.1824|
|L4.1820|
        MOV      r1,r11
        B        |L4.1892|
|L4.1824|
        CMP      r1,r6
        BEQ      |L4.1840|
        CMP      r1,r7
        BEQ      |L4.1840|
        CMP      r1,r12
        BEQ      |L4.1840|
        CMP      r1,r9
        BNE      |L4.1844|
|L4.1840|
        MOV      r1,r10
        B        |L4.1892|
|L4.1844|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1884|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1884|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1884|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1888|
|L4.1884|
        MOV      r1,lr
        B        |L4.1892|
|L4.1888|
        MOV      r1,#0x1000000
|L4.1892|
        LDR      r8,|L4.2436|
        SUB      r8,r8,#0x40
        STR      r1,[r8,#0xc]
        B        |L4.2006|
|L4.1906|
        CMP      r1,r0
        BEQ      |L4.1922|
        CMP      r1,r2
        BEQ      |L4.1922|
        CMP      r1,r3
        BEQ      |L4.1922|
        CMP      r1,r5
        BNE      |L4.1926|
|L4.1922|
        MOV      r1,r11
        B        |L4.1994|
|L4.1926|
        CMP      r1,r6
        BEQ      |L4.1942|
        CMP      r1,r7
        BEQ      |L4.1942|
        CMP      r1,r12
        BEQ      |L4.1942|
        CMP      r1,r9
        BNE      |L4.1946|
|L4.1942|
        MOV      r1,r10
        B        |L4.1994|
|L4.1946|
        LDR      r8,|L4.2436|
        CMP      r1,r8
        BEQ      |L4.1986|
        LDR      r8,|L4.2440|
        CMP      r1,r8
        BEQ      |L4.1986|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BEQ      |L4.1986|
        LDR      r8,|L4.2440|
        ADD      r8,r8,#0x60
        CMP      r1,r8
        BNE      |L4.1990|
|L4.1986|
        MOV      r1,lr
        B        |L4.1994|
|L4.1990|
        MOV      r1,#0x1000000
|L4.1994|
        LDR      r8,|L4.2436|
        SUB      r8,r8,#0x40
        STR      r1,[r8,#8]
|L4.2006|
        MOV      r11,#0x10000
        LDR      r8,|L4.2440|
        MOV      lr,#0x400000
        LDR      r10,|L4.2444|
        LDR      r1,[r4,#0]
        ADD      r8,r8,#0x18
        SUB      r10,r10,#3
        CMP      r1,r8
        BLS      |L4.2116|
        CMP      r1,r0
        BEQ      |L4.2052|
        CMP      r1,r2
        BEQ      |L4.2052|
        CMP      r1,r3
        BEQ      |L4.2052|
        CMP      r1,r5
        BNE      |L4.2056|
|L4.2052|
        MOV      r0,r10
        B        |L4.2110|
|L4.2056|
        CMP      r1,r6
        BEQ      |L4.2072|
        CMP      r1,r7
        BEQ      |L4.2072|
        CMP      r1,r12
        BEQ      |L4.2072|
        CMP      r1,r9
        BNE      |L4.2076|
|L4.2072|
        MOVS     r0,#0x40
        B        |L4.2110|
|L4.2076|
        LDR      r0,|L4.2436|
        CMP      r1,r0
        BEQ      |L4.2104|
        LDR      r0,|L4.2440|
        CMP      r1,r0
        BEQ      |L4.2104|
        LDR      r0,|L4.2436|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BEQ      |L4.2104|
        LDR      r0,|L4.2440|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BNE      |L4.2108|
|L4.2104|
        MOV      r0,r11
        B        |L4.2110|
|L4.2108|
        MOV      r0,lr
|L4.2110|
        LDR      r1,|L4.2440|
        SUBS     r1,r1,#0x34
        B        |L4.2206|
|L4.2116|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x78
        CMP      r1,r8
        BLS      |L4.2210|
        CMP      r1,r0
        BEQ      |L4.2144|
        CMP      r1,r2
        BEQ      |L4.2144|
        CMP      r1,r3
        BEQ      |L4.2144|
        CMP      r1,r5
        BNE      |L4.2148|
|L4.2144|
        MOV      r0,r10
        B        |L4.2202|
|L4.2148|
        CMP      r1,r6
        BEQ      |L4.2164|
        CMP      r1,r7
        BEQ      |L4.2164|
        CMP      r1,r12
        BEQ      |L4.2164|
        CMP      r1,r9
        BNE      |L4.2168|
|L4.2164|
        MOVS     r0,#0x40
        B        |L4.2202|
|L4.2168|
        LDR      r0,|L4.2436|
        CMP      r1,r0
        BEQ      |L4.2196|
        LDR      r0,|L4.2440|
        CMP      r1,r0
        BEQ      |L4.2196|
        LDR      r0,|L4.2436|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BEQ      |L4.2196|
        LDR      r0,|L4.2440|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BNE      |L4.2200|
|L4.2196|
        MOV      r0,r11
        B        |L4.2202|
|L4.2200|
        MOV      r0,lr
|L4.2202|
        LDR      r1,|L4.2440|
        SUBS     r1,r1,#0x38
|L4.2206|
        STR      r0,[r1,#0]
        B        |L4.2384|
|L4.2210|
        LDR      r8,|L4.2436|
        ADD      r8,r8,#0x18
        CMP      r1,r8
        BLS      |L4.2304|
        CMP      r1,r0
        BEQ      |L4.2238|
        CMP      r1,r2
        BEQ      |L4.2238|
        CMP      r1,r3
        BEQ      |L4.2238|
        CMP      r1,r5
        BNE      |L4.2242|
|L4.2238|
        MOV      r0,r10
        B        |L4.2296|
|L4.2242|
        CMP      r1,r6
        BEQ      |L4.2258|
        CMP      r1,r7
        BEQ      |L4.2258|
        CMP      r1,r12
        BEQ      |L4.2258|
        CMP      r1,r9
        BNE      |L4.2262|
|L4.2258|
        MOVS     r0,#0x40
        B        |L4.2296|
|L4.2262|
        LDR      r0,|L4.2436|
        CMP      r1,r0
        BEQ      |L4.2290|
        LDR      r0,|L4.2440|
        CMP      r1,r0
        BEQ      |L4.2290|
        LDR      r0,|L4.2436|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BEQ      |L4.2290|
        LDR      r0,|L4.2440|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BNE      |L4.2294|
|L4.2290|
        MOV      r0,r11
        B        |L4.2296|
|L4.2294|
        MOV      r0,lr
|L4.2296|
        LDR      r1,|L4.2436|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#0xc]
        B        |L4.2384|
|L4.2304|
        CMP      r1,r0
        BEQ      |L4.2320|
        CMP      r1,r2
        BEQ      |L4.2320|
        CMP      r1,r3
        BEQ      |L4.2320|
        CMP      r1,r5
        BNE      |L4.2324|
|L4.2320|
        MOV      r0,r10
        B        |L4.2378|
|L4.2324|
        CMP      r1,r6
        BEQ      |L4.2340|
        CMP      r1,r7
        BEQ      |L4.2340|
        CMP      r1,r12
        BEQ      |L4.2340|
        CMP      r1,r9
        BNE      |L4.2344|
|L4.2340|
        MOVS     r0,#0x40
        B        |L4.2378|
|L4.2344|
        LDR      r0,|L4.2436|
        CMP      r1,r0
        BEQ      |L4.2372|
        LDR      r0,|L4.2440|
        CMP      r1,r0
        BEQ      |L4.2372|
        LDR      r0,|L4.2436|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BEQ      |L4.2372|
        LDR      r0,|L4.2440|
        ADDS     r0,r0,#0x60
        CMP      r1,r0
        BNE      |L4.2376|
|L4.2372|
        MOV      r0,r11
        B        |L4.2378|
|L4.2376|
        MOV      r0,lr
|L4.2378|
        LDR      r1,|L4.2436|
        SUBS     r1,r1,#0x40
        STR      r0,[r1,#8]
|L4.2384|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x16
        STR      r1,[r0,#0]
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x14]
        ORR      r1,r1,#0x80
        STR      r1,[r0,#0x14]
        LDR      r0,[r4,#0x40]
        CBNZ     r0,|L4.2412|
        LDR      r0,[r4,#0x48]
        CBZ      r0,|L4.2422|
|L4.2412|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#8
        STR      r1,[r0,#0]
|L4.2422|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0]
        ORR      r1,r1,#1
        STR      r1,[r0,#0]
        B        |L4.56|
        ENDP

|L4.2436|
        DCD      0x40026040
|L4.2440|
        DCD      0x40026440
|L4.2444|
        DCD      0x00800004

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REVSH|
#line 402
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____RRX|
#line 587
|__asm___22_stm32f7xx_hal_dma_ex_c_af8eecb0____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_DMAEx_ChangeMemory [CODE]
        EXPORT HAL_DMAEx_MultiBufferStart [CODE]
        EXPORT HAL_DMAEx_MultiBufferStart_IT [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP DMA_MultiBufferSetConfig

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
