; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\stm32f7xx_hal_pwr.o --depend=cnn_1\stm32f7xx_hal_pwr.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O0 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\stm32f7xx_hal_pwr.crf ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.HAL_PWR_ConfigPVD||, CODE, READONLY, ALIGN=2

HAL_PWR_ConfigPVD PROC
        LDR      r1,|L1.172|
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0xe0
        LDR      r2,[r0,#0]
        ORRS     r1,r1,r2
        LDR      r2,|L1.172|
        STR      r1,[r2,#0]
        LDR      r1,|L1.176|
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x10000
        LDR      r2,|L1.176|
        STR      r1,[r2,#0]
        SUBS     r1,r2,#4
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x10000
        SUBS     r2,r2,#4
        STR      r1,[r2,#0]
        LDR      r1,|L1.176|
        ADDS     r1,r1,#4
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x10000
        LDR      r2,|L1.176|
        ADDS     r2,r2,#4
        STR      r1,[r2,#0]
        ADDS     r1,r2,#4
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x10000
        ADDS     r2,r2,#4
        STR      r1,[r2,#0]
        LDR      r1,[r0,#4]
        AND      r1,r1,#0x10000
        CMP      r1,#0x10000
        BNE      |L1.96|
        LDR      r1,|L1.176|
        SUBS     r1,r1,#4
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x10000
        LDR      r2,|L1.176|
        SUBS     r2,r2,#4
        STR      r1,[r2,#0]
|L1.96|
        LDR      r1,[r0,#4]
        AND      r1,r1,#0x20000
        CMP      r1,#0x20000
        BNE      |L1.120|
        LDR      r1,|L1.176|
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x10000
        LDR      r2,|L1.176|
        STR      r1,[r2,#0]
|L1.120|
        LDRB     r1,[r0,#4]
        AND      r1,r1,#1
        CBZ      r1,|L1.144|
        LDR      r1,|L1.176|
        ADDS     r1,r1,#4
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x10000
        LDR      r2,|L1.176|
        ADDS     r2,r2,#4
        STR      r1,[r2,#0]
|L1.144|
        LDRB     r1,[r0,#4]
        AND      r1,r1,#2
        CMP      r1,#2
        BNE      |L1.170|
        LDR      r1,|L1.176|
        ADDS     r1,r1,#8
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x10000
        LDR      r2,|L1.176|
        ADDS     r2,r2,#8
        STR      r1,[r2,#0]
|L1.170|
        BX       lr
        ENDP

|L1.172|
        DCD      0x40007000
|L1.176|
        DCD      0x40013c04

        AREA ||i.HAL_PWR_DeInit||, CODE, READONLY, ALIGN=2

HAL_PWR_DeInit PROC
        LDR      r0,|L2.24|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x10000000
        LDR      r1,|L2.24|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x10000000
        STR      r0,[r1,#0]
        BX       lr
        ENDP

|L2.24|
        DCD      0x40023820

        AREA ||i.HAL_PWR_DisableBkUpAccess||, CODE, READONLY, ALIGN=2

HAL_PWR_DisableBkUpAccess PROC
        LDR      r0,|L3.16|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x100
        LDR      r1,|L3.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L3.16|
        DCD      0x40007000

        AREA ||i.HAL_PWR_DisablePVD||, CODE, READONLY, ALIGN=2

HAL_PWR_DisablePVD PROC
        LDR      r0,|L4.16|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x10
        LDR      r1,|L4.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L4.16|
        DCD      0x40007000

        AREA ||i.HAL_PWR_DisableSEVOnPend||, CODE, READONLY, ALIGN=2

HAL_PWR_DisableSEVOnPend PROC
        LDR      r0,|L5.16|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x10
        LDR      r1,|L5.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L5.16|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_DisableSleepOnExit||, CODE, READONLY, ALIGN=2

HAL_PWR_DisableSleepOnExit PROC
        LDR      r0,|L6.16|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#2
        LDR      r1,|L6.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L6.16|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_DisableWakeUpPin||, CODE, READONLY, ALIGN=2

HAL_PWR_DisableWakeUpPin PROC
        LDR      r1,|L7.12|
        LDR      r1,[r1,#0xc]
        BICS     r1,r1,r0
        LDR      r2,|L7.12|
        STR      r1,[r2,#0xc]
        BX       lr
        ENDP

|L7.12|
        DCD      0x40007000

        AREA ||i.HAL_PWR_EnableBkUpAccess||, CODE, READONLY, ALIGN=2

HAL_PWR_EnableBkUpAccess PROC
        LDR      r0,|L8.16|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x100
        LDR      r1,|L8.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L8.16|
        DCD      0x40007000

        AREA ||i.HAL_PWR_EnablePVD||, CODE, READONLY, ALIGN=2

HAL_PWR_EnablePVD PROC
        LDR      r0,|L9.16|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x10
        LDR      r1,|L9.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L9.16|
        DCD      0x40007000

        AREA ||i.HAL_PWR_EnableSEVOnPend||, CODE, READONLY, ALIGN=2

HAL_PWR_EnableSEVOnPend PROC
        LDR      r0,|L10.16|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x10
        LDR      r1,|L10.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L10.16|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_EnableSleepOnExit||, CODE, READONLY, ALIGN=2

HAL_PWR_EnableSleepOnExit PROC
        LDR      r0,|L11.16|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#2
        LDR      r1,|L11.16|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L11.16|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_EnableWakeUpPin||, CODE, READONLY, ALIGN=2

HAL_PWR_EnableWakeUpPin PROC
        LDR      r1,|L12.36|
        LDR      r1,[r1,#0xc]
        AND      r2,r0,#0x3f00
        ORRS     r1,r1,r2
        LDR      r2,|L12.36|
        STR      r1,[r2,#0xc]
        MOV      r1,r2
        LDR      r1,[r1,#8]
        AND      r2,r0,#0x3f00
        BICS     r1,r1,r2
        ORR      r1,r1,r0,LSR #6
        LDR      r2,|L12.36|
        STR      r1,[r2,#8]
        BX       lr
        ENDP

        DCW      0x0000
|L12.36|
        DCD      0x40007000

        AREA ||i.HAL_PWR_EnterSLEEPMode||, CODE, READONLY, ALIGN=2

HAL_PWR_EnterSLEEPMode PROC
        LDR      r2,|L13.28|
        LDR      r2,[r2,#0]
        BIC      r2,r2,#4
        LDR      r3,|L13.28|
        STR      r2,[r3,#0]
        CMP      r1,#1
        BNE      |L13.20|
        WFI      
        B        |L13.26|
|L13.20|
        SEV      
        WFE      
        WFE      
|L13.26|
        BX       lr
        ENDP

|L13.28|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_EnterSTANDBYMode||, CODE, READONLY, ALIGN=2

HAL_PWR_EnterSTANDBYMode PROC
        LDR      r0,|L14.32|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#2
        LDR      r1,|L14.32|
        STR      r0,[r1,#0]
        LDR      r0,|L14.36|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#4
        LDR      r1,|L14.36|
        STR      r0,[r1,#0]
        NOP      
        NOP      
        WFI      
        BX       lr
        ENDP

|L14.32|
        DCD      0x40007000
|L14.36|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_EnterSTOPMode||, CODE, READONLY, ALIGN=2

HAL_PWR_EnterSTOPMode PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        MOVS     r0,#0
        LDR      r3,|L15.60|
        LDR      r0,[r3,#0]
        BIC      r0,r0,#3
        ORRS     r0,r0,r2
        STR      r0,[r3,#0]
        LDR      r3,|L15.64|
        LDR      r3,[r3,#0]
        ORR      r3,r3,#4
        LDR      r4,|L15.64|
        STR      r3,[r4,#0]
        CMP      r1,#1
        BNE      |L15.38|
        WFI      
        B        |L15.44|
|L15.38|
        SEV      
        WFE      
        WFE      
|L15.44|
        LDR      r3,|L15.64|
        LDR      r3,[r3,#0]
        BIC      r3,r3,#4
        LDR      r4,|L15.64|
        STR      r3,[r4,#0]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L15.60|
        DCD      0x40007000
|L15.64|
        DCD      0xe000ed10

        AREA ||i.HAL_PWR_PVDCallback||, CODE, READONLY, ALIGN=1

HAL_PWR_PVDCallback PROC
        BX       lr
        ENDP


        AREA ||i.HAL_PWR_PVD_IRQHandler||, CODE, READONLY, ALIGN=2

HAL_PWR_PVD_IRQHandler PROC
        PUSH     {r4,lr}
        LDR      r0,|L17.28|
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x10000
        CBZ      r0,|L17.24|
        BL       HAL_PWR_PVDCallback
        MOV      r0,#0x10000
        LDR      r1,|L17.28|
        STR      r0,[r1,#0]
|L17.24|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L17.28|
        DCD      0x40013c14

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____REVSH|
#line 402
|__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____RRX|
#line 587
|__asm___19_stm32f7xx_hal_pwr_c_f2cfe8be____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT HAL_PWR_ConfigPVD [CODE]
        EXPORT HAL_PWR_DeInit [CODE]
        EXPORT HAL_PWR_DisableBkUpAccess [CODE]
        EXPORT HAL_PWR_DisablePVD [CODE]
        EXPORT HAL_PWR_DisableSEVOnPend [CODE]
        EXPORT HAL_PWR_DisableSleepOnExit [CODE]
        EXPORT HAL_PWR_DisableWakeUpPin [CODE]
        EXPORT HAL_PWR_EnableBkUpAccess [CODE]
        EXPORT HAL_PWR_EnablePVD [CODE]
        EXPORT HAL_PWR_EnableSEVOnPend [CODE]
        EXPORT HAL_PWR_EnableSleepOnExit [CODE]
        EXPORT HAL_PWR_EnableWakeUpPin [CODE]
        EXPORT HAL_PWR_EnterSLEEPMode [CODE]
        EXPORT HAL_PWR_EnterSTANDBYMode [CODE]
        EXPORT HAL_PWR_EnterSTOPMode [CODE]
        EXPORT HAL_PWR_PVDCallback [CODE,WEAK]
        EXPORT HAL_PWR_PVD_IRQHandler [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
