; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\system_stm32f7xx.o --depend=cnn_1\system_stm32f7xx.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O0 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\system_stm32f7xx.crf ../Src/system_stm32f7xx.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.SystemCoreClockUpdate||, CODE, READONLY, ALIGN=2

SystemCoreClockUpdate PROC
        PUSH     {r4-r6,lr}
        MOVS     r0,#0
        MOVS     r2,#0
        MOVS     r3,#2
        MOVS     r4,#0
        MOVS     r1,#2
        LDR      r5,|L1.172|
        LDR      r5,[r5,#0]
        AND      r0,r5,#0xc
        CBZ      r0,|L1.32|
        CMP      r0,#4
        BEQ      |L1.40|
        CMP      r0,#8
        BNE      |L1.136|
        B        |L1.48|
|L1.32|
        LDR      r5,|L1.176|
        LDR      r6,|L1.180|
        STR      r5,[r6,#0]  ; SystemCoreClock
        B        |L1.144|
|L1.40|
        LDR      r5,|L1.184|
        LDR      r6,|L1.180|
        STR      r5,[r6,#0]  ; SystemCoreClock
        B        |L1.144|
|L1.48|
        LDR      r5,|L1.172|
        SUBS     r5,r5,#4
        LDR      r5,[r5,#0]
        UBFX     r4,r5,#22,#1
        LDR      r5,|L1.172|
        SUBS     r5,r5,#4
        LDR      r5,[r5,#0]
        AND      r1,r5,#0x3f
        CBZ      r4,|L1.92|
        LDR      r5,|L1.184|
        UDIV     r5,r5,r1
        LDR      r6,|L1.172|
        SUBS     r6,r6,#4
        LDR      r6,[r6,#0]
        UBFX     r6,r6,#6,#9
        MUL      r2,r5,r6
        B        |L1.112|
|L1.92|
        LDR      r5,|L1.176|
        UDIV     r5,r5,r1
        LDR      r6,|L1.172|
        SUBS     r6,r6,#4
        LDR      r6,[r6,#0]
        UBFX     r6,r6,#6,#9
        MUL      r2,r5,r6
|L1.112|
        LDR      r5,|L1.172|
        SUBS     r5,r5,#4
        LDR      r5,[r5,#0]
        UBFX     r5,r5,#16,#2
        ADDS     r5,r5,#1
        LSLS     r3,r5,#1
        UDIV     r5,r2,r3
        LDR      r6,|L1.180|
        STR      r5,[r6,#0]  ; SystemCoreClock
        B        |L1.144|
|L1.136|
        LDR      r5,|L1.176|
        LDR      r6,|L1.180|
        STR      r5,[r6,#0]  ; SystemCoreClock
        NOP      
|L1.144|
        NOP      
        LDR      r5,|L1.172|
        LDR      r5,[r5,#0]
        UBFX     r5,r5,#4,#4
        LDR      r6,|L1.188|
        LDRB     r0,[r6,r5]
        LDR      r5,|L1.180|
        LDR      r5,[r5,#0]  ; SystemCoreClock
        LSRS     r5,r5,r0
        LDR      r6,|L1.180|
        STR      r5,[r6,#0]  ; SystemCoreClock
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L1.172|
        DCD      0x40023808
|L1.176|
        DCD      0x00f42400
|L1.180|
        DCD      SystemCoreClock
|L1.184|
        DCD      0x017d7840
|L1.188|
        DCD      AHBPrescTable

        AREA ||i.SystemInit||, CODE, READONLY, ALIGN=2

SystemInit PROC
        LDR      r0,|L2.68|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#1
        LDR      r1,|L2.68|
        STR      r0,[r1,#0]
        MOVS     r0,#0
        LDR      r1,|L2.68|
        ADDS     r1,r1,#8
        STR      r0,[r1,#0]
        LDR      r0,|L2.68|
        LDR      r0,[r0,#0]
        LDR      r1,|L2.72|
        ANDS     r0,r0,r1
        LDR      r1,|L2.68|
        STR      r0,[r1,#0]
        LDR      r0,|L2.76|
        ADDS     r1,r1,#4
        STR      r0,[r1,#0]
        SUBS     r0,r1,#4
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x40000
        SUBS     r1,r1,#4
        STR      r0,[r1,#0]
        MOVS     r0,#0
        LDR      r1,|L2.68|
        ADDS     r1,r1,#0xc
        STR      r0,[r1,#0]
        MOV      r0,#0x8000000
        LDR      r1,|L2.80|
        STR      r0,[r1,#0]
        BX       lr
        ENDP

|L2.68|
        DCD      0x40023800
|L2.72|
        DCD      0xfef6ffff
|L2.76|
        DCD      0x24003010
|L2.80|
        DCD      0xe000ed08

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=0

AHBPrescTable
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x01,0x02,0x03,0x04
        DCB      0x06,0x07,0x08,0x09
APBPrescTable
        DCB      0x00,0x00,0x00,0x00
        DCB      0x01,0x02,0x03,0x04

        AREA ||.data||, DATA, ALIGN=2

SystemCoreClock
        DCD      0x00f42400

;*** Start embedded assembler ***

#line 1 "../Src/system_stm32f7xx.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___18_system_stm32f7xx_c_5d646a67____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____REVSH|
#line 402
|__asm___18_system_stm32f7xx_c_5d646a67____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____RRX|
#line 587
|__asm___18_system_stm32f7xx_c_5d646a67____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT SystemCoreClockUpdate [CODE]
        EXPORT SystemInit [CODE]
        EXPORT AHBPrescTable [DATA,SIZE=16]
        EXPORT APBPrescTable [DATA,SIZE=8]
        EXPORT SystemCoreClock [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
