; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\system_stm32f7xx.o --depend=cnn_1\system_stm32f7xx.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O3 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\system_stm32f7xx.crf ../Src/system_stm32f7xx.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.SystemCoreClockUpdate||, CODE, READONLY, ALIGN=2

SystemCoreClockUpdate PROC
        PUSH     {r4-r6,lr}
        LDR      r4,|L1.112|
        LDR      r2,|L1.116|
        LDR      r0,|L1.120|
        LDR      r1,[r4,#0]
        ANDS     r1,r1,#0xc
        BEQ      |L1.26|
        LDR      r5,|L1.124|
        CMP      r1,#4
        BEQ      |L1.30|
        CMP      r1,#8
        BEQ      |L1.34|
|L1.26|
        STR      r2,[r0,#0]  ; SystemCoreClock
        B        |L1.92|
|L1.30|
        STR      r5,[r0,#0]  ; SystemCoreClock
        B        |L1.92|
|L1.34|
        LDR      r1,|L1.112|
        SUBS     r1,r1,#4
        LDR      r6,[r1,#0]
        LDR      r3,[r1,#0]
        AND      r3,r3,#0x3f
        UBFX     r6,r6,#22,#1
        CBZ      r6,|L1.64|
        LDR      r6,[r1,#0]
        UDIV     r2,r5,r3
        UBFX     r3,r6,#6,#9
        B        |L1.74|
|L1.64|
        LDR      r5,[r1,#0]
        UDIV     r2,r2,r3
        UBFX     r3,r5,#6,#9
|L1.74|
        LDR      r1,[r1,#0]
        MULS     r2,r3,r2
        UBFX     r1,r1,#16,#2
        ADDS     r1,r1,#1
        LSLS     r1,r1,#1
        UDIV     r1,r2,r1
        STR      r1,[r0,#0]  ; SystemCoreClock
|L1.92|
        LDR      r1,[r4,#0]
        LDR      r3,|L1.128|
        LDR      r2,[r0,#0]  ; SystemCoreClock
        UBFX     r1,r1,#4,#4
        LDRB     r1,[r3,r1]
        LSRS     r2,r2,r1
        STR      r2,[r0,#0]  ; SystemCoreClock
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L1.112|
        DCD      0x40023808
|L1.116|
        DCD      0x00f42400
|L1.120|
        DCD      ||.data||
|L1.124|
        DCD      0x017d7840
|L1.128|
        DCD      ||.constdata||

        AREA ||i.SystemInit||, CODE, READONLY, ALIGN=2

SystemInit PROC
        LDR      r0,|L2.56|
        MOVS     r1,#0
        PUSH     {r4,r5,lr}
        LDR      r4,[r0,#0]
        LDR      r2,|L2.56|
        LDR      r3,|L2.60|
        ORR      r4,r4,#1
        ADDS     r2,r2,#8
        STR      r4,[r0,#0]
        STR      r1,[r2,#0]
        LDR      r2,[r0,#0]
        ADDS     r5,r0,#4
        LDR      r4,|L2.64|
        ANDS     r2,r2,r3
        STR      r2,[r0,#0]
        STR      r4,[r5,#0]
        LDR      r5,[r0,#0]
        LDR      r2,|L2.56|
        BIC      r5,r5,#0x40000
        STR      r5,[r0,#0]
        ADDS     r2,r2,#0xc
        LSLS     r3,r4,#23
        LDR      r4,|L2.68|
        STR      r1,[r2,#0]
        STR      r3,[r4,#0]
        POP      {r4,r5,pc}
        ENDP

|L2.56|
        DCD      0x40023800
|L2.60|
        DCD      0xfef6ffff
|L2.64|
        DCD      0x24003010
|L2.68|
        DCD      0xe000ed08

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=0

AHBPrescTable
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x01,0x02,0x03,0x04
        DCB      0x06,0x07,0x08,0x09

        AREA ||area_number.6||, DATA, READONLY, ALIGN=0

        EXPORTAS ||area_number.6||, ||.constdata||
APBPrescTable
        DCB      0x00,0x00,0x00,0x00
        DCB      0x01,0x02,0x03,0x04

        AREA ||.data||, DATA, ALIGN=2

SystemCoreClock
        DCD      0x00f42400

;*** Start embedded assembler ***

#line 1 "../Src/system_stm32f7xx.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___18_system_stm32f7xx_c_5d646a67____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____REVSH|
#line 402
|__asm___18_system_stm32f7xx_c_5d646a67____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___18_system_stm32f7xx_c_5d646a67____RRX|
#line 587
|__asm___18_system_stm32f7xx_c_5d646a67____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT SystemCoreClockUpdate [CODE]
        EXPORT SystemInit [CODE]
        EXPORT AHBPrescTable [DATA,SIZE=16]
        EXPORT APBPrescTable [DATA,SIZE=8]
        EXPORT SystemCoreClock [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
