; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -ocnn_1\unicode.o --depend=cnn_1\unicode.d --cpu=Cortex-M7 --fpu=SoftVFP --apcs=interwork -O0 --diag_suppress=9931 -I../Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FatFs/src/drivers -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/FatFs/src -I../Drivers/CMSIS/Include -I..\..\..\..\STM32_Project -I..\..\..\STM32F7_Project -I..\..\..\..\LKML_C\Src -I..\..\..\..\LKML_C -I.\RTE\_CNN_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F7xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F7xx\Include -D__MICROLIB -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F746xx -DUSE_HAL_DRIVER -DSTM32F746xx --omf_browse=cnn_1\unicode.crf ..\Middlewares\Third_Party\FatFs\src\option\unicode.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.ff_convert||, CODE, READONLY, ALIGN=2

ff_convert PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        CMP      r2,#0x80
        BGE      |L1.12|
        MOV      r0,r2
        B        |L1.68|
|L1.12|
        CBZ      r1,|L1.36|
        CMP      r2,#0xff
        BLE      |L1.22|
        MOVS     r3,#0
        B        |L1.32|
|L1.22|
        SUB      r3,r2,#0x80
        LDR      r4,|L1.72|
        LDRH     r3,[r4,r3,LSL #1]
|L1.32|
        MOV      r0,r3
        B        |L1.68|
|L1.36|
        MOVS     r0,#0
        B        |L1.56|
|L1.40|
        LDR      r3,|L1.72|
        LDRH     r3,[r3,r0,LSL #1]
        CMP      r3,r2
        BNE      |L1.52|
        B        |L1.60|
|L1.52|
        ADDS     r3,r0,#1
        UXTH     r0,r3
|L1.56|
        CMP      r0,#0x80
        BLT      |L1.40|
|L1.60|
        NOP      
        ADD      r3,r0,#0x80
        UXTB     r0,r3
|L1.68|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.72|
        DCD      Tbl

        AREA ||i.ff_wtoupper||, CODE, READONLY, ALIGN=2

ff_wtoupper PROC
        MOV      r2,r0
        MOVS     r1,#0
        B        |L2.8|
|L2.6|
        ADDS     r1,r1,#1
|L2.8|
        LDR      r0,|L2.48|
        LDRH     r0,[r0,r1,LSL #1]
        CBZ      r0,|L2.26|
        LDR      r0,|L2.48|
        LDRH     r0,[r0,r1,LSL #1]
        CMP      r0,r2
        BNE      |L2.6|
|L2.26|
        LDR      r0,|L2.48|
        LDRH     r0,[r0,r1,LSL #1]
        CBZ      r0,|L2.42|
        LDR      r0,|L2.52|
        LDRH     r0,[r0,r1,LSL #1]
|L2.40|
        BX       lr
|L2.42|
        MOV      r0,r2
        B        |L2.40|
        ENDP

        DCW      0x0000
|L2.48|
        DCD      tbl_lower
|L2.52|
        DCD      tbl_upper

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=1

Tbl
        DCW      0x00c7,0x00fc
        DCW      0x00e9,0x00e2
        DCW      0x00e4,0x00e0
        DCW      0x00e5,0x00e7
        DCW      0x00ea,0x00eb
        DCW      0x00e8,0x00ef
        DCW      0x00ee,0x00ec
        DCW      0x00c4,0x00c5
        DCW      0x00c9,0x00e6
        DCW      0x00c6,0x00f4
        DCW      0x00f6,0x00f2
        DCW      0x00fb,0x00f9
        DCW      0x00ff,0x00d6
        DCW      0x00dc,0x00f8
        DCW      0x00a3,0x00d8
        DCW      0x00d7,0x0192
        DCW      0x00e1,0x00ed
        DCW      0x00f3,0x00fa
        DCW      0x00f1,0x00d1
        DCW      0x00aa,0x00ba
        DCW      0x00bf,0x00ae
        DCW      0x00ac,0x00bd
        DCW      0x00bc,0x00a1
        DCW      0x00ab,0x00bb
        DCW      0x2591,0x2592
        DCW      0x2593,0x2502
        DCW      0x2524,0x00c1
        DCW      0x00c2,0x00c0
        DCW      0x00a9,0x2563
        DCW      0x2551,0x2557
        DCW      0x255d,0x00a2
        DCW      0x00a5,0x2510
        DCW      0x2514,0x2534
        DCW      0x252c,0x251c
        DCW      0x2500,0x253c
        DCW      0x00e3,0x00c3
        DCW      0x255a,0x2554
        DCW      0x2569,0x2566
        DCW      0x2560,0x2550
        DCW      0x256c,0x00a4
        DCW      0x00f0,0x00d0
        DCW      0x00ca,0x00cb
        DCW      0x00c8,0x0131
        DCW      0x00cd,0x00ce
        DCW      0x00cf,0x2518
        DCW      0x250c,0x2588
        DCW      0x2584,0x00a6
        DCW      0x00cc,0x2580
        DCW      0x00d3,0x00df
        DCW      0x00d4,0x00d2
        DCW      0x00f5,0x00d5
        DCW      0x00b5,0x00fe
        DCW      0x00de,0x00da
        DCW      0x00db,0x00d9
        DCW      0x00fd,0x00dd
        DCW      0x00af,0x00b4
        DCW      0x00ad,0x00b1
        DCW      0x2017,0x00be
        DCW      0x00b6,0x00a7
        DCW      0x00f7,0x00b8
        DCW      0x00b0,0x00a8
        DCW      0x00b7,0x00b9
        DCW      0x00b3,0x00b2
        DCW      0x25a0,0x00a0
tbl_lower
        DCW      0x0061,0x0062
        DCW      0x0063,0x0064
        DCW      0x0065,0x0066
        DCW      0x0067,0x0068
        DCW      0x0069,0x006a
        DCW      0x006b,0x006c
        DCW      0x006d,0x006e
        DCW      0x006f,0x0070
        DCW      0x0071,0x0072
        DCW      0x0073,0x0074
        DCW      0x0075,0x0076
        DCW      0x0077,0x0078
        DCW      0x0079,0x007a
        DCW      0x00a1,0x00a2
        DCW      0x00a3,0x00a5
        DCW      0x00ac,0x00af
        DCW      0x00e0,0x00e1
        DCW      0x00e2,0x00e3
        DCW      0x00e4,0x00e5
        DCW      0x00e6,0x00e7
        DCW      0x00e8,0x00e9
        DCW      0x00ea,0x00eb
        DCW      0x00ec,0x00ed
        DCW      0x00ee,0x00ef
        DCW      0x00f0,0x00f1
        DCW      0x00f2,0x00f3
        DCW      0x00f4,0x00f5
        DCW      0x00f6,0x00f8
        DCW      0x00f9,0x00fa
        DCW      0x00fb,0x00fc
        DCW      0x00fd,0x00fe
        DCW      0x00ff,0x0101
        DCW      0x0103,0x0105
        DCW      0x0107,0x0109
        DCW      0x010b,0x010d
        DCW      0x010f,0x0111
        DCW      0x0113,0x0115
        DCW      0x0117,0x0119
        DCW      0x011b,0x011d
        DCW      0x011f,0x0121
        DCW      0x0123,0x0125
        DCW      0x0127,0x0129
        DCW      0x012b,0x012d
        DCW      0x012f,0x0131
        DCW      0x0133,0x0135
        DCW      0x0137,0x013a
        DCW      0x013c,0x013e
        DCW      0x0140,0x0142
        DCW      0x0144,0x0146
        DCW      0x0148,0x014b
        DCW      0x014d,0x014f
        DCW      0x0151,0x0153
        DCW      0x0155,0x0157
        DCW      0x0159,0x015b
        DCW      0x015d,0x015f
        DCW      0x0161,0x0163
        DCW      0x0165,0x0167
        DCW      0x0169,0x016b
        DCW      0x016d,0x016f
        DCW      0x0171,0x0173
        DCW      0x0175,0x0177
        DCW      0x017a,0x017c
        DCW      0x017e,0x0192
        DCW      0x03b1,0x03b2
        DCW      0x03b3,0x03b4
        DCW      0x03b5,0x03b6
        DCW      0x03b7,0x03b8
        DCW      0x03b9,0x03ba
        DCW      0x03bb,0x03bc
        DCW      0x03bd,0x03be
        DCW      0x03bf,0x03c0
        DCW      0x03c1,0x03c3
        DCW      0x03c4,0x03c5
        DCW      0x03c6,0x03c7
        DCW      0x03c8,0x03c9
        DCW      0x03ca,0x0430
        DCW      0x0431,0x0432
        DCW      0x0433,0x0434
        DCW      0x0435,0x0436
        DCW      0x0437,0x0438
        DCW      0x0439,0x043a
        DCW      0x043b,0x043c
        DCW      0x043d,0x043e
        DCW      0x043f,0x0440
        DCW      0x0441,0x0442
        DCW      0x0443,0x0444
        DCW      0x0445,0x0446
        DCW      0x0447,0x0448
        DCW      0x0449,0x044a
        DCW      0x044b,0x044c
        DCW      0x044d,0x044e
        DCW      0x044f,0x0451
        DCW      0x0452,0x0453
        DCW      0x0454,0x0455
        DCW      0x0456,0x0457
        DCW      0x0458,0x0459
        DCW      0x045a,0x045b
        DCW      0x045c,0x045e
        DCW      0x045f,0x2170
        DCW      0x2171,0x2172
        DCW      0x2173,0x2174
        DCW      0x2175,0x2176
        DCW      0x2177,0x2178
        DCW      0x2179,0x217a
        DCW      0x217b,0x217c
        DCW      0x217d,0x217e
        DCW      0x217f,0xff41
        DCW      0xff42,0xff43
        DCW      0xff44,0xff45
        DCW      0xff46,0xff47
        DCW      0xff48,0xff49
        DCW      0xff4a,0xff4b
        DCW      0xff4c,0xff4d
        DCW      0xff4e,0xff4f
        DCW      0xff50,0xff51
        DCW      0xff52,0xff53
        DCW      0xff54,0xff55
        DCW      0xff56,0xff57
        DCW      0xff58,0xff59
        DCW      0xff5a,0x0000
tbl_upper
        DCW      0x0041,0x0042
        DCW      0x0043,0x0044
        DCW      0x0045,0x0046
        DCW      0x0047,0x0048
        DCW      0x0049,0x004a
        DCW      0x004b,0x004c
        DCW      0x004d,0x004e
        DCW      0x004f,0x0050
        DCW      0x0051,0x0052
        DCW      0x0053,0x0054
        DCW      0x0055,0x0056
        DCW      0x0057,0x0058
        DCW      0x0059,0x005a
        DCW      0x0021,0xffe0
        DCW      0xffe1,0xffe5
        DCW      0xffe2,0xffe3
        DCW      0x00c0,0x00c1
        DCW      0x00c2,0x00c3
        DCW      0x00c4,0x00c5
        DCW      0x00c6,0x00c7
        DCW      0x00c8,0x00c9
        DCW      0x00ca,0x00cb
        DCW      0x00cc,0x00cd
        DCW      0x00ce,0x00cf
        DCW      0x00d0,0x00d1
        DCW      0x00d2,0x00d3
        DCW      0x00d4,0x00d5
        DCW      0x00d6,0x00d8
        DCW      0x00d9,0x00da
        DCW      0x00db,0x00dc
        DCW      0x00dd,0x00de
        DCW      0x0178,0x0100
        DCW      0x0102,0x0104
        DCW      0x0106,0x0108
        DCW      0x010a,0x010c
        DCW      0x010e,0x0110
        DCW      0x0112,0x0114
        DCW      0x0116,0x0118
        DCW      0x011a,0x011c
        DCW      0x011e,0x0120
        DCW      0x0122,0x0124
        DCW      0x0126,0x0128
        DCW      0x012a,0x012c
        DCW      0x012e,0x0130
        DCW      0x0132,0x0134
        DCW      0x0136,0x0139
        DCW      0x013b,0x013d
        DCW      0x013f,0x0141
        DCW      0x0143,0x0145
        DCW      0x0147,0x014a
        DCW      0x014c,0x014e
        DCW      0x0150,0x0152
        DCW      0x0154,0x0156
        DCW      0x0158,0x015a
        DCW      0x015c,0x015e
        DCW      0x0160,0x0162
        DCW      0x0164,0x0166
        DCW      0x0168,0x016a
        DCW      0x016c,0x016e
        DCW      0x0170,0x0172
        DCW      0x0174,0x0176
        DCW      0x0179,0x017b
        DCW      0x017d,0x0191
        DCW      0x0391,0x0392
        DCW      0x0393,0x0394
        DCW      0x0395,0x0396
        DCW      0x0397,0x0398
        DCW      0x0399,0x039a
        DCW      0x039b,0x039c
        DCW      0x039d,0x039e
        DCW      0x039f,0x03a0
        DCW      0x03a1,0x03a3
        DCW      0x03a4,0x03a5
        DCW      0x03a6,0x03a7
        DCW      0x03a8,0x03a9
        DCW      0x03aa,0x0410
        DCW      0x0411,0x0412
        DCW      0x0413,0x0414
        DCW      0x0415,0x0416
        DCW      0x0417,0x0418
        DCW      0x0419,0x041a
        DCW      0x041b,0x041c
        DCW      0x041d,0x041e
        DCW      0x041f,0x0420
        DCW      0x0421,0x0422
        DCW      0x0423,0x0424
        DCW      0x0425,0x0426
        DCW      0x0427,0x0428
        DCW      0x0429,0x042a
        DCW      0x042b,0x042c
        DCW      0x042d,0x042e
        DCW      0x042f,0x0401
        DCW      0x0402,0x0403
        DCW      0x0404,0x0405
        DCW      0x0406,0x0407
        DCW      0x0408,0x0409
        DCW      0x040a,0x040b
        DCW      0x040c,0x040e
        DCW      0x040f,0x2160
        DCW      0x2161,0x2162
        DCW      0x2163,0x2164
        DCW      0x2165,0x2166
        DCW      0x2167,0x2168
        DCW      0x2169,0x216a
        DCW      0x216b,0x216c
        DCW      0x216d,0x216e
        DCW      0x216f,0xff21
        DCW      0xff22,0xff23
        DCW      0xff24,0xff25
        DCW      0xff26,0xff27
        DCW      0xff28,0xff29
        DCW      0xff2a,0xff2b
        DCW      0xff2c,0xff2d
        DCW      0xff2e,0xff2f
        DCW      0xff30,0xff31
        DCW      0xff32,0xff33
        DCW      0xff34,0xff35
        DCW      0xff36,0xff37
        DCW      0xff38,0xff39
        DCW      0xff3a,0x0000

;*** Start embedded assembler ***

#line 1 "..\\Middlewares\\Third_Party\\FatFs\\src\\option\\unicode.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___9_unicode_c_b3db7f04____REV16|
#line 388 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___9_unicode_c_b3db7f04____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___9_unicode_c_b3db7f04____REVSH|
#line 402
|__asm___9_unicode_c_b3db7f04____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___9_unicode_c_b3db7f04____RRX|
#line 587
|__asm___9_unicode_c_b3db7f04____RRX| PROC
#line 588

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT ff_convert [CODE]
        EXPORT ff_wtoupper [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP Tbl
        KEEP tbl_lower
        KEEP tbl_upper

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
